/** Danish strings. Keys are the English UI strings. Missing keys fall back to English (see scripts/i18n-keys.mjs --missing). */
export const da: Record<string, string> = {
 "Try saying": "Prøv at sige",
 "Time to train": "Tid til at træne",
 "That’s a lot — check the amount": "Det er meget — tjek mængden",
 "Logged 1 set": "Loggede 1 sæt",
 "Log 1 item": "Log 1 ting",
 "Log 1 exercise": "Log 1 øvelse",
 "exercise": "øvelse",
 "Add 1 exercise": "Tilføj 1 øvelse",
 "\"—\" means no data, not zero. \"≥\" means some entries had no value for it.": "\"—\" betyder ingen data, ikke nul. \"≥\" betyder, at nogle poster mangler en værdi.",
 "\"—\" means the source has no value — it is not counted as zero.": "\"—\" betyder, at kilden ikke har en værdi — den tælles ikke som nul.",
 "+ Warm-up": "+ Opvarmning",
 "12 weeks": "12 uger",
 "15 seconds less": "15 sekunder mindre",
 "15 seconds more": "15 sekunder mere",
 "4 weeks": "4 uger",
 "6 months": "6 måneder",
 "A bit of everything": "Lidt af det hele",
 "A new version of Aven is ready.": "En ny version af Aven er klar.",
 "A record beats your previous best for that exact measure. First-time exercises set a baseline, not a record. Tap an exercise to see the definitions.": "En rekord slår din tidligere bedste for præcis det mål. Første gang en øvelse logges, sætter den et udgangspunkt, ikke en rekord. Tryk på en øvelse for at se definitionerne.",
 "A routine is a list of exercises with planned sets and rep ranges. Build one, or set up a starter plan.": "Et program er en liste af øvelser med planlagte sæt og rep-intervaller. Lav et selv, eller start med en startplan.",
 "A simple, conventional template matched to your goal, experience and equipment — a place to start, not a prescription.": "En enkel, klassisk skabelon tilpasset dit mål, din erfaring og dit udstyr — et sted at starte, ikke en ordination.",
 "A web app can only notify you while Aven is open or installed and running in the background. Reliable scheduled reminders when the app is closed need a push server, which isn’t built yet. Rest-timer alerts (sound and vibration) work while you train.": "En webapp kan kun give dig besked, mens Aven er åben eller installeret og kører i baggrunden. Pålidelige påmindelser, når appen er lukket, kræver en push-server, som endnu ikke er bygget. Hviletimer-alarmer (lyd og vibration) virker, mens du træner.",
 "About Aven": "Om Aven",
 "Active workout": "Aktiv træning",
 "Activity is logged for your records. It is never added to your calorie targets.": "Aktivitet logges til dine optegnelser. Den lægges aldrig oven i dine kaloriemål.",
 "Activity logged": "Aktivitet logget",
 "Add": "Tilføj",
 "Add exercise": "Tilføj øvelse",
 "Add exercises": "Tilføj øvelser",
 "Add exercises, or dictate what you did.": "Tilføj øvelser, eller indtal, hvad du har lavet.",
 "Add food": "Tilføj mad",
 "Add ingredient — search foods": "Tilføj ingrediens — søg i fødevarer",
 "Add meal": "Tilføj måltid",
 "Add photo": "Tilføj foto",
 "Add portion": "Tilføj portion",
 "Add the exercises for this session.": "Tilføj øvelserne til denne træning.",
 "Add this product": "Tilføj dette produkt",
 "Add to": "Tilføj til",
 "Add to current workout": "Tilføj til nuværende træning",
 "Add to {meal}": "Tilføj til {meal}",
 "Add your first ingredient below.": "Tilføj din første ingrediens herunder.",
 "Add {n} exercises": "Tilføj {n} øvelser",
 "Added to workout": "Tilføjet til træningen",
 "Added to {meal}": "Tilføjet til {meal}",
 "Added {name}": "Tilføjede {name}",
 "Added {n} items to {meal}": "Tilføjede {n} ting til {meal}",
 "All": "Alle",
 "All optional. Leave a field empty to track it without a target. Aven never changes these for you — including after exercise.": "Alt er valgfrit. Lad et felt stå tomt for at spore uden mål. Aven ændrer aldrig disse for dig — heller ikke efter træning.",
 "Allow camera access in your browser settings, or type the number below.": "Giv adgang til kameraet i din browsers indstillinger, eller skriv nummeret herunder.",
 "Allow notifications": "Tillad notifikationer",
 "Also": "Desuden",
 "Amount": "Mængde",
 "Appearance": "Udseende",
 "Arm": "Arm",
 "Assisted": "Assisteret",
 "Aven": "Aven",
 "Aven doesn’t prescribe targets. If you’re unsure, a dietitian or coach can help you choose.": "Aven foreskriver ikke mål. Er du i tvivl, kan en diætist eller træner hjælpe dig med at vælge.",
 "Aven has no account and no analytics. Your workouts, meals, weight and photos are stored in this browser’s local storage and IndexedDB.": "Aven har ingen konto og ingen analytics. Dine træninger, måltider, vægt og fotos gemmes i denne browsers lokale lager og IndexedDB.",
 "Back": "Tilbage",
 "Backup downloaded": "Sikkerhedskopi hentet",
 "Backup restored": "Sikkerhedskopi gendannet",
 "Barbell": "Stang",
 "Barcode (optional)": "Stregkode (valgfri)",
 "Barcode lookup isn’t available right now. You can add this product yourself.": "Opslag på stregkode er ikke tilgængeligt lige nu. Du kan selv tilføje produktet.",
 "Barcode number": "Stregkodenummer",
 "Best set volume": "Bedste sæt-volumen",
 "Biceps": "Biceps",
 "Blank fields are stored as unknown, not zero.": "Tomme felter gemmes som ukendt, ikke nul.",
 "Body measurements": "Kropsmål",
 "Bodyweight": "Kropsvægt",
 "Brand (optional)": "Mærke (valgfri)",
 "Breakfast": "Morgenmad",
 "Build a routine": "Lav et program",
 "Build muscle": "Opbyg muskler",
 "Build routine": "Lav program",
 "Bundled foods are approximate reference values. Online results come from Open Food Facts (© contributors, ODbL — open database licence) and USDA FoodData Central (public domain, CC0).": "Medfølgende fødevarer er omtrentlige referenceværdier. Online-resultater kommer fra Open Food Facts (© bidragydere, ODbL — åben databaselicens) og USDA FoodData Central (almindeligt tilgængelig, CC0).",
 "Bundled foods, your saved foods and manual entry all still work.": "Medfølgende fødevarer, dine gemte fødevarer og manuel indtastning virker stadig.",
 "Bundled reference values are typical averages. Correct them by making your own copy.": "Medfølgende referenceværdier er typiske gennemsnit. Ret dem ved at lave din egen kopi.",
 "Calories": "Kalorier",
 "Calories and macros are optional — set them any time.": "Kalorier og makroer er valgfrie — sæt dem når som helst.",
 "Calories and macros differ by more than 25% (4/4/9 kcal per g). Double-check — alcohol and fibre can explain some of it.": "Kalorier og makroer afviger med mere end 25 % (4/4/9 kcal pr. g). Tjek igen — alkohol og fibre kan forklare noget af det.",
 "Calories and macros differ by more than 25%. Check the label — alcohol and fibre can explain some of it.": "Kalorier og makroer afviger med mere end 25 %. Tjek etiketten — alkohol og fibre kan forklare noget af det.",
 "Calories per day": "Kalorier pr. dag",
 "Calories, macros, water — optional": "Kalorier, makroer, vand — valgfrit",
 "Calves": "Lægge",
 "Camera permission was denied.": "Adgang til kameraet blev afvist.",
 "Camera scanning isn’t supported in this browser.": "Kameraskanning understøttes ikke i denne browser.",
 "Cancel": "Annuller",
 "Carbs": "Kulhydrat",
 "Change": "Skift",
 "Changing a food never rewrites entries you already logged.": "Ændringer af en fødevare omskriver aldrig poster, du allerede har logget.",
 "Check and confirm": "Tjek og bekræft",
 "Chest": "Bryst",
 "Choose": "Vælg",
 "Choose file": "Vælg fil",
 "Clear": "Ryd",
 "Clear day": "Ryd dagen",
 "Clear meal": "Ryd måltid",
 "Clear nutrition targets": "Ryd ernæringsmål",
 "Clearing browser data removes everything. Export a backup first (Data & backup).": "Rydder du browserdata, forsvinder alt. Lav først en sikkerhedskopi (Data og backup).",
 "Close": "Luk",
 "Combine ingredients once, then log servings in two taps.": "Saml ingredienser én gang, og log derefter portioner med to tryk.",
 "Complete set": "Afslut sæt",
 "Confirm": "Bekræft",
 "Continue": "Fortsæt",
 "Cooked": "Tilberedt",
 "Copied {n} entries to {day}": "Kopierede {n} poster til {day}",
 "Copy": "Kopiér",
 "Copy day to…": "Kopiér dag til…",
 "Copy meal to…": "Kopiér måltid til…",
 "Copy to day": "Kopiér til dag",
 "Copy to {day}": "Kopiér til {day}",
 "Copy to…": "Kopiér til…",
 "Correct → my copy": "Ret → min kopi",
 "Couldn’t listen": "Kunne ikke lytte",
 "Couldn’t save that photo": "Kunne ikke gemme fotoet",
 "Couldn’t save to this browser’s storage. Export a backup now.": "Kunne ikke gemme i browserens lager. Lav en sikkerhedskopi nu.",
 "Couldn’t start the camera.": "Kunne ikke starte kameraet.",
 "Create a routine first, then schedule it here.": "Lav først et program, og planlæg det så her.",
 "Create a starter plan": "Opret en startplan",
 "Create custom exercise": "Opret egen øvelse",
 "Create exercise": "Opret øvelse",
 "Create food": "Opret fødevare",
 "Create it once and it is yours to reuse.": "Opret den én gang, så kan du bruge den igen.",
 "Create it once and it stays in your library.": "Opret den én gang, så bliver den i dit bibliotek.",
 "Create your own foods and recipes — they are kept on this device.": "Opret dine egne fødevarer og opskrifter — de gemmes på denne enhed.",
 "Create “{q}”": "Opret “{q}”",
 "Cues, seat height, how it felt…": "Tips, sædehøjde, hvordan det føltes…",
 "Custom": "Egen",
 "Custom exercise": "Egen øvelse",
 "Daily goal": "Dagligt mål",
 "Dansk": "Dansk",
 "Dark": "Mørk",
 "Data & backup": "Data og backup",
 "Date": "Dato",
 "Dates and numbers follow your language. Distance and measurements follow your weight unit; change them individually in Settings.": "Datoer og tal følger dit sprog. Afstand og mål følger din vægtenhed; ændr dem enkeltvis i Indstillinger.",
 "Day": "Dag",
 "Day options": "Dagsvalg",
 "Days with nothing logged are faded and left out of averages — they are not zero-calorie days.": "Dage uden logning er toned ned og holdes uden for gennemsnit — de er ikke dage med nul kalorier.",
 "Default rest between sets": "Standardhvile mellem sæt",
 "Delete": "Slet",
 "Delete all data": "Slet alle data",
 "Delete entry": "Slet post",
 "Delete everything": "Slet alt",
 "Delete recipe": "Slet opskrift",
 "Delete routine": "Slet program",
 "Delete set": "Slet sæt",
 "Deleted": "Slettet",
 "Demo data": "Demodata",
 "Demo data loaded": "Demodata indlæst",
 "Demo data loaded — remove it any time in Settings": "Demodata indlæst — fjern dem når som helst i Indstillinger",
 "Demo data removed": "Demodata fjernet",
 "Density": "Densitet",
 "Density (g per ml) — only if you know it": "Densitet (g pr. ml) — kun hvis du kender den",
 "Details": "Detaljer",
 "Diagram: front and back. Orange = main muscle, tint = helpers. No video demonstration is included.": "Diagram: forfra og bagfra. Orange = hovedmuskel, nuance = hjælpemuskler. Ingen videodemonstration er medtaget.",
 "Dictate": "Indtal",
 "Dictate sets": "Indtal sæt",
 "Dictation": "Diktering",
 "Didn’t catch anything. Tap the sphere to try again, or type it.": "Jeg hørte ikke noget. Tryk på kuglen for at prøve igen, eller skriv det.",
 "Dinner": "Aftensmad",
 "Discard workout": "Kassér træning",
 "Discard workout?": "Kassér træning?",
 "Dismiss": "Afvis",
 "Distance": "Afstand",
 "Do it today": "Gør det i dag",
 "Done": "Færdig",
 "Done for today": "Færdig for i dag",
 "Done speaking": "Færdig med at tale",
 "Download backup": "Hent sikkerhedskopi",
 "Dry": "Tør",
 "Dumbbell": "Håndvægt",
 "Duplicate": "Dupliker",
 "Duplicated": "Duplikeret",
 "Duration": "Varighed",
 "Eaten": "Spist",
 "Eaten today": "Spist i dag",
 "Edit": "Rediger",
 "Edit entry": "Rediger post",
 "Edit exercise": "Rediger øvelse",
 "Edit food": "Rediger fødevare",
 "Edit quick amounts": "Rediger hurtige mængder",
 "Edit recipe": "Rediger opskrift",
 "Edit routine": "Rediger program",
 "Edit text": "Rediger tekst",
 "Edits change this record only. Personal-record flags are not recalculated.": "Rettelser ændrer kun denne optegnelse. Rekordmærker genberegnes ikke.",
 "Effort (RPE/RIR) can be turned on in Settings.": "Anstrengelse (RPE/RIR) kan slås til i Indstillinger.",
 "Effort tracking": "Anstrengelsessporing",
 "Empty": "Tom",
 "Empty session": "Tom træning",
 "Endurance": "Udholdenhed",
 "English": "English",
 "Enter reps first": "Skriv reps først",
 "Entries moved to {meal}": "Poster flyttet til {meal}",
 "Epley: weight × (1 + reps ÷ 30), sets of up to 12 reps — an estimate, not a tested max": "Epley: vægt × (1 + reps ÷ 30), sæt på op til 12 reps — et estimat, ikke et testet maks",
 "Equipment": "Udstyr",
 "Estimated 1RM": "Estimeret 1RM",
 "Estimated 1RM over time": "Estimeret 1RM over tid",
 "Everything stays on this device.": "Alt bliver på denne enhed.",
 "Exercise": "Øvelse",
 "Exercise details": "Øvelsesdetaljer",
 "Exercise note": "Øvelsesnote",
 "Exercise options": "Øvelsesvalg",
 "Exercise removed": "Øvelse fjernet",
 "Exercise trends": "Øvelsestendenser",
 "Exercises": "Øvelser",
 "Experienced": "Erfaren",
 "Explore with demo data instead": "Udforsk med demodata i stedet",
 "Export backup": "Eksportér sikkerhedskopi",
 "Export, import, delete": "Eksportér, importér, slet",
 "Fat": "Fedt",
 "Favourite": "Favorit",
 "Favourites": "Favoritter",
 "Fibre": "Fibre",
 "Finish": "Afslut",
 "Finish and save {n} sets": "Afslut og gem {n} sæt",
 "Finish workout": "Afslut træning",
 "Finish workout?": "Afslut træning?",
 "Finish your current workout first": "Afslut først din nuværende træning",
 "Finished workouts and activities land here, and stay editable.": "Afsluttede træninger og aktiviteter havner her og kan stadig redigeres.",
 "Fixed weekdays": "Faste ugedage",
 "Flexible rotation": "Fleksibel rotation",
 "Food": "Mad",
 "Food & water": "Mad og vand",
 "Food data": "Fødevaredata",
 "Food lookup": "Fødevareopslag",
 "Food updated — past entries keep their old values": "Fødevare opdateret — tidligere poster beholder deres gamle værdier",
 "Foods you log will show up here for one-tap repeats.": "Fødevarer, du logger, dukker op her, så du kan gentage dem med ét tryk.",
 "Forearms": "Underarme",
 "Full": "Fuld",
 "General fitness": "Generel fitness",
 "Get stronger": "Bliv stærkere",
 "Getting started": "Kom i gang",
 "Glutes": "Baller",
 "Go": "Kør",
 "Go to day": "Gå til dag",
 "Goal": "Mål",
 "Good afternoon": "God eftermiddag",
 "Good evening": "God aften",
 "Good morning": "God morgen",
 "Grams (solids)": "Gram (fast føde)",
 "Grams are hidden: this food has no known density.": "Gram er skjult: denne fødevare har ingen kendt densitet.",
 "Hamstrings": "Baglår",
 "Haptic feedback": "Haptisk feedback",
 "Haptics work on devices and browsers that support vibration (mostly Android).": "Haptik virker på enheder og browsere med vibration (mest Android).",
 "Heavier lifts, lower reps": "Tungere løft, færre reps",
 "Heaviest set": "Tungeste sæt",
 "Heaviest weight lifted for 1+ reps": "Tungeste vægt løftet for 1+ reps",
 "Higher reps, shorter rests": "Flere reps, kortere hvil",
 "Highest reps in one working set": "Flest reps i ét arbejdssæt",
 "Hips": "Hofter",
 "History": "Historik",
 "Hit {n} sessions in a week to start a streak.": "Nå {n} træninger på en uge for at starte en stime.",
 "Honest limits": "Ærlige begrænsninger",
 "How did it feel?": "Hvordan føltes det?",
 "How is it logged?": "Hvordan logges den?",
 "How it’s going": "Sådan går det",
 "How much?": "Hvor meget?",
 "How to": "Sådan gør du",
 "Hunger, cravings, eating out…": "Sult, trang, spise ude…",
 "I couldn’t find any foods in that. Try “150 grams of rice and a banana”.": "Jeg kunne ikke finde nogen fødevarer i det. Prøv “150 gram ris og en banan”.",
 "Import backup": "Importér sikkerhedskopi",
 "In progress": "I gang",
 "Include photos": "Medtag fotos",
 "Include progress photos (larger file)": "Medtag fremgangsfotos (større fil)",
 "Ingredients": "Ingredienser",
 "Instructions (one step per line, optional)": "Instruktioner (ét trin pr. linje, valgfrit)",
 "Into meal": "Ind i måltid",
 "Just this day": "Kun denne dag",
 "Keep": "Behold",
 "Keep training": "Fortsæt træningen",
 "Kettlebell": "Kettlebell",
 "Label": "Betegnelse",
 "Language": "Sprog",
 "Last": "Sidst",
 "Late night": "Sen aften",
 "Late-night meals before this hour count toward the previous day.": "Sene måltider før dette tidspunkt tæller med til den forrige dag.",
 "Less": "Mindre",
 "Let’s set up Aven.": "Lad os sætte Aven op.",
 "Library": "Bibliotek",
 "Light": "Lys",
 "Listening": "Lytter",
 "Listening (no level meter)": "Lytter (uden niveaumåler)",
 "Load demo data": "Indlæs demodata",
 "Load × reps": "Vægt × reps",
 "Log": "Log",
 "Log a workout, a meal or your weight and this page fills in. Charts only show what you have actually recorded.": "Log en træning, et måltid eller din vægt, så fyldes siden ud. Diagrammer viser kun det, du faktisk har registreret.",
 "Log activity": "Log aktivitet",
 "Log as you go, or build a routine and let Aven line up your week.": "Log undervejs, eller lav et program og lad Aven lægge din uge.",
 "Log calories and macros without picking a food.": "Log kalorier og makroer uden at vælge en fødevare.",
 "Log cardio / recovery": "Log cardio / restitution",
 "Log cardio or recovery": "Log cardio eller restitution",
 "Log food": "Log mad",
 "Log on day": "Log på dag",
 "Log your weight": "Log din vægt",
 "Log your weight to see a trend. Weigh-ins are noisy — the trend line smooths them.": "Log din vægt for at se en tendens. Vejninger svinger — tendenslinjen udjævner dem.",
 "Log {n} exercises": "Log {n} øvelser",
 "Log {n} items": "Log {n} ting",
 "Logged": "Logget",
 "Logged {n} sets": "Loggede {n} sæt",
 "Longest distance": "Længste afstand",
 "Longest hold": "Længste hold",
 "Longest single working set": "Længste enkelte arbejdssæt",
 "Look up": "Slå op",
 "Lookup is rate-limited — try again shortly": "Opslag er begrænset — prøv igen om lidt",
 "Lookup is rate-limited — try again shortly.": "Opslag er begrænset — prøv igen om lidt.",
 "Lose fat": "Tab fedt",
 "Lunch": "Frokost",
 "Made-up workouts, meals and weigh-ins so you can explore every screen. Clearly labelled, removable.": "Opdigtede træninger, måltider og vejninger, så du kan udforske alle skærme. Tydeligt mærket og kan fjernes.",
 "Make warm-up": "Gør til opvarmning",
 "Make working set": "Gør til arbejdssæt",
 "Mark set not done": "Markér sæt som ikke færdigt",
 "Matched": "Matchet",
 "Meal": "Måltid",
 "Meal options": "Måltidsvalg",
 "Meals": "Måltider",
 "Meals, quick amounts, lookup": "Måltider, hurtige mængder, opslag",
 "Measured in": "Måles i",
 "Measurement": "Mål",
 "Measurements": "Mål",
 "Microphone or speech permission was denied. You can allow it in your browser settings, or type instead.": "Adgang til mikrofon eller tale blev afvist. Du kan tillade det i browserens indstillinger, eller skrive i stedet.",
 "Microphone unavailable": "Mikrofon utilgængelig",
 "Millilitres (drinks)": "Milliliter (drikke)",
 "Millilitres are hidden: this food has no known density, so ml ≠ g can’t be assumed.": "Milliliter er skjult: denne fødevare har ingen kendt densitet, så ml ≠ g kan ikke antages.",
 "Min": "Min",
 "Minimise workout": "Minimér træning",
 "Minutes": "Minutter",
 "Missed": "Overset",
 "Missed workouts": "Oversete træninger",
 "Monday": "Mandag",
 "More": "Mere",
 "More filters": "Flere filtre",
 "More nutrients": "Flere næringsstoffer",
 "More nutrients, portions and details": "Flere næringsstoffer, portioner og detaljer",
 "Most reps": "Flest reps",
 "Most reps in a set": "Flest reps i et sæt",
 "Motion": "Bevægelse",
 "Move down": "Flyt ned",
 "Move them or skip — your history is never changed.": "Flyt dem eller spring over — din historik ændres aldrig.",
 "Move to…": "Flyt til…",
 "Move up": "Flyt op",
 "Moved {name} to {day}": "Flyttede {name} til {day}",
 "Movement": "Bevægelse",
 "Muscles (first tapped = primary)": "Muskler (første tryk = primær)",
 "My foods": "Mine fødevarer",
 "Name": "Navn",
 "Neck": "Nakke",
 "Needed to convert between grams and millilitres. Leave blank if unsure.": "Bruges til at omregne mellem gram og milliliter. Lad feltet stå tomt, hvis du er i tvivl.",
 "New": "Ny",
 "New day starts at": "Ny dag starter kl.",
 "New exercise": "Ny øvelse",
 "New food": "Ny fødevare",
 "New meal": "Nyt måltid",
 "New recipe": "Ny opskrift",
 "New routine": "Nyt program",
 "Next day": "Næste dag",
 "Next month": "Næste måned",
 "Nice work": "Flot arbejde",
 "No cloud sync or accounts. No photo-based food estimation. No AI coaching — progression suggestions are simple rules based on your own last session. Background reminders need a push server.": "Ingen skysynkronisering eller konti. Ingen fotobaseret madestimering. Ingen AI-coaching — progressionsforslag er simple regler baseret på din egen seneste træning. Baggrundspåmindelser kræver en push-server.",
 "No entries for this day": "Ingen poster for denne dag",
 "No exercise found": "Ingen øvelse fundet",
 "No exercise matched “{q}”": "Ingen øvelse matchede “{q}”",
 "No favourites yet": "Ingen favoritter endnu",
 "No fixed days. Aven lines up the next routine in the order below and moves on when you finish it.": "Ingen faste dage. Aven stiller det næste program op i rækkefølgen herunder og går videre, når du er færdig.",
 "No history yet": "Ingen historik endnu",
 "No instructions yet.": "Ingen instruktioner endnu.",
 "No match for “{q}”": "Ingen match for “{q}”",
 "No microphone was found or it is in use by another app.": "Der blev ikke fundet nogen mikrofon, eller den bruges af en anden app.",
 "No new records this time. First-time exercises set a baseline — records need something to beat.": "Ingen nye rekorder denne gang. Øvelser, du logger første gang, sætter et udgangspunkt — rekorder skal have noget at slå.",
 "No personal foods yet": "Ingen egne fødevarer endnu",
 "No photos yet": "Ingen fotos endnu",
 "No product found for {c}. You can add it yourself.": "Intet produkt fundet for {c}. Du kan tilføje det selv.",
 "No recipes yet": "Ingen opskrifter endnu",
 "No routines yet": "Ingen programmer endnu",
 "No saved meals yet": "Ingen gemte måltider endnu",
 "No sets found. Try “80 kilos for 8”.": "Ingen sæt fundet. Prøv “80 kilo for 8”.",
 "No workout is running — confirming will start one.": "Ingen træning kører — bekræfter du, startes en.",
 "Not found": "Ikke fundet",
 "Not this food?": "Ikke denne fødevare?",
 "Note": "Note",
 "Notes": "Noter",
 "Nothing extra online.": "Intet ekstra online.",
 "Nothing has been logged yet. You can undo this right after.": "Der er ikke logget noget endnu. Du kan fortryde lige bagefter.",
 "Nothing is recorded or sent anywhere.": "Intet optages eller sendes nogen steder hen.",
 "Nothing logged yet": "Intet logget endnu",
 "Nothing logged yet.": "Intet logget endnu.",
 "Nothing planned today": "Intet planlagt i dag",
 "Nothing to add": "Intet at tilføje",
 "Nothing to chart yet": "Intet at vise endnu",
 "Nothing yet today.": "Intet endnu i dag.",
 "Notifications are allowed. Aven will remind you at that time on planned training days while it is running.": "Notifikationer er tilladt. Aven minder dig på det tidspunkt på planlagte træningsdage, mens den kører.",
 "Notifications are blocked in your browser. You’ll see an in-app nudge on Today instead.": "Notifikationer er blokeret i din browser. Du får i stedet et skub i appen under I dag.",
 "Numbers and dates follow your language. Decimal commas and points both work when typing. Values are stored in metric and converted for display.": "Tal og datoer følger dit sprog. Både decimalkomma og -punktum virker, når du skriver. Værdier gemmes metrisk og omregnes ved visning.",
 "Nutrition": "Ernæring",
 "Nutrition targets": "Ernæringsmål",
 "Nutrition values are…": "Næringsværdier er…",
 "Off": "Fra",
 "One JSON file with everything: workouts, food, plans, settings.": "Én JSON-fil med det hele: træninger, mad, planer, indstillinger.",
 "One number starts your trend.": "Ét tal starter din tendens.",
 "One weigh-in so far. A second one starts the trend line.": "Kun én vejning indtil videre. En anden starter tendenslinjen.",
 "One-off change. Your repeating plan stays the same.": "Engangsændring. Din gentagne plan forbliver den samme.",
 "Online food lookup": "Online fødevareopslag",
 "Online lookup": "Online opslag",
 "Online lookup isn’t available": "Online opslag er ikke tilgængeligt",
 "Only available on an empty app, so it can’t mix with your real records.": "Kun tilgængelig i en tom app, så det ikke blandes med dine rigtige data.",
 "Only what my equipment allows": "Kun det mit udstyr tillader",
 "Open a meal in your diary, tap ⋯ and choose “Save as meal”.": "Åbn et måltid i din dagbog, tryk på ⋯ og vælg “Gem som måltid”.",
 "Open log": "Åbn log",
 "Optional": "Valgfrit",
 "Optional. Skip to simply track what you eat; set targets whenever you like.": "Valgfrit. Spring over for blot at spore, hvad du spiser; sæt mål, når du har lyst.",
 "Optional. Stored on this device.": "Valgfrit. Gemmes på denne enhed.",
 "Options": "Valg",
 "Over target": "Over mål",
 "Pause": "Pause",
 "Paused": "På pause",
 "Paused — the clock is stopped. Logging a set resumes it.": "På pause — uret er stoppet. Logger du et sæt, genoptages det.",
 "Per serving": "Pr. portion",
 "Permanently erases all Aven data and photos from this device.": "Sletter permanent alle Aven-data og fotos fra denne enhed.",
 "Personal food": "Egen fødevare",
 "Personal records": "Personlige rekorder",
 "Photo": "Foto",
 "Photo deleted": "Foto slettet",
 "Photo saved privately on this device": "Foto gemt privat på denne enhed",
 "Photos": "Fotos",
 "Pick": "Vælg",
 "Pick a day": "Vælg en dag",
 "Pick a routine for each training day. Missed days can be moved without touching your history.": "Vælg et program til hver træningsdag. Oversete dage kan flyttes uden at røre din historik.",
 "Pick date": "Vælg dato",
 "Pick the days you usually train. Flexible rotations are available later.": "Vælg de dage, du plejer at træne. Fleksible rotationer kan vælges senere.",
 "Pick training days first": "Vælg først træningsdage",
 "Plan": "Plan",
 "Planned sets and rep ranges are targets. What you actually do is saved separately in each workout.": "Planlagte sæt og rep-intervaller er mål. Det, du rent faktisk gør, gemmes separat i hver træning.",
 "Planned vs done": "Planlagt vs. gjort",
 "Planning ahead — entries save to this day.": "Planlægger frem — poster gemmes på denne dag.",
 "Portion size is a typical estimate — adjust if you know the weight.": "Portionsstørrelsen er et typisk skøn — ret den, hvis du kender vægten.",
 "Portions": "Portioner",
 "Prepared as": "Tilberedt som",
 "Prepared weight": "Færdig vægt",
 "Prev": "Sidst",
 "Previous day": "Forrige dag",
 "Previous month": "Forrige måned",
 "Privacy": "Privatliv",
 "Private by design: photos stay on this device, are shrunk and stripped of location data, and are never uploaded or included in exports unless you choose.": "Privat fra start: fotos bliver på denne enhed, formindskes og mister placeringsdata, og de uploades aldrig eller medtages i eksport, medmindre du vælger det.",
 "Product data comes from Open Food Facts when the lookup server is reachable; your saved foods are checked first.": "Produktdata kommer fra Open Food Facts, når opslagsserveren kan nås; dine gemte fødevarer tjekkes først.",
 "Progress": "Fremgang",
 "Progress photo": "Fremgangsfoto",
 "Progress photos": "Fremgangsfotos",
 "Protein": "Protein",
 "Protein per day": "Protein pr. dag",
 "Pull": "Træk",
 "Quads": "Forlår",
 "Quick add": "Hurtig tilføjelse",
 "Quick amount": "Hurtig mængde",
 "Quick amounts (ml)": "Hurtige mængder (ml)",
 "Quick entry": "Hurtig post",
 "Quick entry added": "Hurtig post tilføjet",
 "RIR": "RIR",
 "RPE": "RPE",
 "RPE = how hard (1–10). RIR = reps left in the tank. Adds a column to each set.": "RPE = hvor hårdt (1–10). RIR = reps tilbage i tanken. Tilføjer en kolonne til hvert sæt.",
 "Raw": "Rå",
 "Raw and cooked weights are not interchangeable — cooking changes water content.": "Rå og tilberedte vægte kan ikke byttes om — tilberedning ændrer vandindholdet.",
 "Ready to restore": "Klar til gendannelse",
 "Ready.": "Klar.",
 "Recent": "Seneste",
 "Recent activity": "Seneste aktivitet",
 "Recent records": "Seneste rekorder",
 "Recent sessions": "Seneste træninger",
 "Recipe": "Opskrift",
 "Recipe saved — past entries are unchanged": "Opskrift gemt — tidligere poster er uændrede",
 "Recipes": "Opskrifter",
 "Redo setup": "Gentag opsætning",
 "Reduced": "Reduceret",
 "Reduced motion removes springs, slides and the sphere’s movement. Everything stays usable.": "Reduceret bevægelse fjerner fjedring, glidninger og kuglens bevægelse. Alt forbliver brugbart.",
 "Reference (approximate)": "Reference (omtrentlig)",
 "Remaining": "Tilbage",
 "Remembered": "Husket",
 "Reminders": "Påmindelser",
 "Remove": "Fjern",
 "Remove demo data": "Fjern demodata",
 "Remove exercise": "Fjern øvelse",
 "Remove favourite": "Fjern favorit",
 "Remove set": "Fjern sæt",
 "Removed": "Fjernet",
 "Rename, add or remove meals. Removing a meal keeps its entries, which move to the first meal.": "Omdøb, tilføj eller fjern måltider. Fjerner du et måltid, flyttes posterne til det første måltid.",
 "Rep range": "Rep-interval",
 "Repeat": "Gentag",
 "Repeating plan": "Gentagen plan",
 "Replace exercise": "Udskift øvelse",
 "Replace my data": "Erstat mine data",
 "Replaces everything on this device. You can undo right after.": "Erstatter alt på denne enhed. Du kan fortryde lige bagefter.",
 "Reps": "Reps",
 "Reschedule": "Omplanlæg",
 "Rescheduled": "Omplanlagt",
 "Rest": "Hvil",
 "Rest (seconds)": "Hvil (sekunder)",
 "Rest after a set": "Hvil efter et sæt",
 "Rest day": "Hviledag",
 "Rest over": "Hvilen er slut",
 "Rest-timer sound": "Lyd ved hviletimer",
 "Resume": "Genoptag",
 "Resume current": "Genoptag nuværende",
 "Resume workout": "Genoptag træning",
 "Reuse these foods in one tap": "Genbrug disse fødevarer med ét tryk",
 "Review": "Gennemse",
 "Routine": "Program",
 "Routine deleted": "Program slettet",
 "Routine saved": "Program gemt",
 "Routines": "Programmer",
 "Runs, walks, mobility, warm-ups — with duration and distance": "Løb, gåture, mobilitet, opvarmning — med varighed og afstand",
 "Same main muscle and movement; equipment you have comes first.": "Samme hovedmuskel og bevægelse; udstyr, du har, kommer først.",
 "Saturated fat": "Mættet fedt",
 "Save": "Gem",
 "Save activity": "Gem aktivitet",
 "Save as meal": "Gem som måltid",
 "Save as routine": "Gem som program",
 "Save changes": "Gem ændringer",
 "Save exercise": "Gem øvelse",
 "Save food": "Gem fødevare",
 "Save my copy": "Gem min kopi",
 "Save recipe": "Gem opskrift",
 "Save routine": "Gem program",
 "Saved": "Gemt",
 "Saved as routine": "Gemt som program",
 "Saved automatically.": "Gemmes automatisk.",
 "Saved changes": "Ændringer gemt",
 "Saved meals": "Gemte måltider",
 "Saved “{name}”": "Gemte “{name}”",
 "Say what you ate": "Sig, hvad du har spist",
 "Scan": "Scan",
 "Scan barcode": "Scan stregkode",
 "Schedule": "Planlæg",
 "Search Open Food Facts and USDA through Aven’s server. Off = bundled and personal foods only.": "Søg i Open Food Facts og USDA via Avens server. Fra = kun medfølgende og egne fødevarer.",
 "Search exercises": "Søg øvelser",
 "Search foods": "Søg fødevarer",
 "Search foods and brands": "Søg fødevarer og mærker",
 "Search something else": "Søg efter noget andet",
 "Search, scan, dictate or copy a meal. Logging a repeat takes two taps.": "Søg, scan, indtal eller kopiér et måltid. At logge en gentagelse tager to tryk.",
 "Searching Open Food Facts and USDA…": "Søger i Open Food Facts og USDA…",
 "Seconds": "Sekunder",
 "Select exercises": "Vælg øvelser",
 "Serving size": "Portionsstørrelse",
 "Servings": "Portioner",
 "Session note": "Træningsnote",
 "Sessions": "Træninger",
 "Sessions per week": "Træninger pr. uge",
 "Set": "Sæt",
 "Set deleted": "Sæt slettet",
 "Set options": "Sætvalg",
 "Set removed": "Sæt fjernet",
 "Set targets": "Sæt mål",
 "Set your targets": "Sæt dine mål",
 "Sets": "Sæt",
 "Settings": "Indstillinger",
 "Setup": "Opsætning",
 "Shoulders": "Skuldre",
 "Show as table": "Vis som tabel",
 "Show chart": "Vis diagram",
 "Six quick questions. Skip any of them — you can change everything later.": "Seks hurtige spørgsmål. Spring over, hvad du vil — du kan ændre alt senere.",
 "Skip": "Spring over",
 "Skip all": "Spring alt over",
 "Skip it": "Spring over",
 "Skipped": "Sprunget over",
 "Sleep, energy, niggles…": "Søvn, energi, småskavanker…",
 "Smallest weight jump": "Mindste vægtspring",
 "Snacks": "Snacks",
 "Sodium": "Natrium",
 "Some": "Lidt",
 "Some ingredients are in ml with no known density — enter the prepared weight so serving sizes can be computed.": "Nogle ingredienser er i ml uden kendt densitet — skriv den færdige vægt, så portionsstørrelser kan beregnes.",
 "Speak instead": "Tal i stedet",
 "Speech recognition couldn’t start.": "Talegenkendelsen kunne ikke starte.",
 "Speech recognition isn’t available in this browser. Type it, or use your keyboard’s microphone key.": "Talegenkendelse er ikke tilgængelig i denne browser. Skriv det, eller brug mikrofontasten på dit tastatur.",
 "Speech recognition stopped unexpectedly.": "Talegenkendelsen stoppede uventet.",
 "Speech-to-text is done by your browser’s speech service (often a cloud service). Audio is never stored by Aven.": "Tale-til-tekst udføres af din browsers talefunktion (ofte en skytjeneste). Aven gemmer aldrig lyd.",
 "Squat": "Squat",
 "Start": "Start",
 "Start again": "Start igen",
 "Start listening": "Begynd at lytte",
 "Start typing to find food": "Begynd at skrive for at finde mad",
 "Start workout": "Start træning",
 "Start your first session": "Start din første træning",
 "Starter plan": "Startplan",
 "Starter plan created — edit it in Train": "Startplan oprettet — rediger den under Træn",
 "Starting camera…": "Starter kamera…",
 "Starting the microphone…": "Starter mikrofonen…",
 "Stop and review": "Stop og gennemse",
 "Storage is full — export a backup and free space.": "Lageret er fuldt — eksportér en sikkerhedskopi og frigør plads.",
 "Substitutions": "Alternativer",
 "Sugars": "Sukkerarter",
 "Suggested substitutes": "Foreslåede alternativer",
 "Sunday": "Søndag",
 "Superset": "Superset",
 "Superset with next": "Superset med næste",
 "System": "System",
 "Tap the sphere and speak": "Tryk på kuglen og tal",
 "Tap the star on any food to keep it close.": "Tryk på stjernen ved en fødevare for at have den ved hånden.",
 "Target sessions per week": "Mål for træninger pr. uge",
 "Targets": "Mål",
 "Targets set to {w} {u}": "Mål sat til {w} {u}",
 "That backup is from a newer version of Aven.": "Den sikkerhedskopi er fra en nyere version af Aven.",
 "That file isn’t a valid Aven backup.": "Den fil er ikke en gyldig Aven-sikkerhedskopi.",
 "The browser’s speech service isn’t reachable (it needs a connection). Type instead — nothing was recorded.": "Browserens talefunktion kan ikke nås (den kræver forbindelse). Skriv i stedet — intet blev optaget.",
 "The original stays untouched; yours is used from now on.": "Originalen forbliver uændret; din bruges fremover.",
 "Theme": "Tema",
 "Thigh": "Lår",
 "This browser doesn’t support notifications. You’ll see an in-app nudge on Today instead.": "Denne browser understøtter ikke notifikationer. Du får i stedet et skub i appen under I dag.",
 "This portion": "Denne portion",
 "This week": "Denne uge",
 "Time": "Tid",
 "Today": "I dag",
 "Today’s workout": "Dagens træning",
 "Tomorrow": "I morgen",
 "Train": "Træn",
 "Train again": "Træn igen",
 "Train anyway, or pick one of your routines.": "Træn alligevel, eller vælg et af dine programmer.",
 "Training": "Træning",
 "Training consistency": "Træningskonsistens",
 "Training plus food awareness": "Træning plus madbevidsthed",
 "Training, food and progress in one place.": "Træning, mad og fremgang ét sted.",
 "Training-day reminder": "Påmindelse på træningsdage",
 "Trend": "Tendens",
 "Trend (estimate)": "Tendens (estimat)",
 "Trend rate needs 7+ days of data": "Tendenshastighed kræver 7+ dages data",
 "Triceps": "Triceps",
 "Try {w} {u} — all sets reached {reps} reps last time. Tap to set.": "Prøv {w} {u} — alle sæt nåede {reps} reps sidst. Tryk for at sætte.",
 "Try “squat 100 kilos for 5, 5 and 5”.": "Prøv “squat 100 kilo for 5, 5 og 5”.",
 "Type instead": "Skriv i stedet",
 "Type the number below instead.": "Skriv nummeret herunder i stedet.",
 "Type the number under the barcode instead.": "Skriv nummeret under stregkoden i stedet.",
 "Type what you ate or did": "Skriv, hvad du spiste eller lavede",
 "Typical size, not verified": "Typisk størrelse, ikke verificeret",
 "Understanding…": "Forstår…",
 "Undo": "Fortryd",
 "Unit not available": "Enhed ikke tilgængelig",
 "Units & language": "Enheder og sprog",
 "Units & locale": "Enheder og region",
 "Unknown exercise": "Ukendt øvelse",
 "Unlink superset": "Fjern superset",
 "Update": "Opdatér",
 "Updated {day}": "Opdaterede {day}",
 "Use previous": "Brug forrige",
 "Used for progression suggestions.": "Bruges til progressionsforslag.",
 "Verified serving size": "Verificeret portionsstørrelse",
 "View": "Se",
 "Volume": "Volumen",
 "Volume = weight × reps of completed working sets. Bodyweight and timed exercises count as zero here.": "Volumen = vægt × reps for afsluttede arbejdssæt. Kropsvægts- og tidsøvelser tæller som nul her.",
 "Volume = weight × reps of completed working sets. Warm-ups and unchecked sets are not counted.": "Volumen = vægt × reps for afsluttede arbejdssæt. Opvarmning og ikke-afkrydsede sæt tæller ikke med.",
 "Volume and progression": "Volumen og progression",
 "Waist": "Talje",
 "Warm-up sets": "Opvarmningssæt",
 "Water": "Vand",
 "Water quick amounts (ml)": "Hurtige vandmængder (ml)",
 "Week of": "Uge fra",
 "Week starts on": "Ugen starter på",
 "Weekly volume": "Ugentlig volumen",
 "Weigh at a consistent time — single readings are noisy; Aven charts a smoothed trend.": "Vej dig på samme tidspunkt — enkeltmålinger svinger; Aven viser en udjævnet tendens.",
 "Weigh the finished dish for accurate servings. Without it, the ingredient weights are added up.": "Vej den færdige ret for præcise portioner. Uden den lægges ingrediensernes vægt sammen.",
 "Weigh-ins": "Vejninger",
 "Weight": "Vægt",
 "Weight logged": "Vægt logget",
 "Weight × reps in one working set": "Vægt × reps i ét arbejdssæt",
 "What can you train with?": "Hvad kan du træne med?",
 "What should I call you?": "Hvad skal jeg kalde dig?",
 "What’s simulated or not built": "Hvad der er simuleret eller ikke bygget",
 "What’s your main goal?": "Hvad er dit hovedmål?",
 "Which days can you train?": "Hvilke dage kan du træne?",
 "Which exercise?": "Hvilken øvelse?",
 "Which “{q}”?": "Hvilken “{q}”?",
 "Whole recipe": "Hele opskriften",
 "Working sets": "Arbejdssæt",
 "Working…": "Arbejder…",
 "Workout": "Træning",
 "Workout deleted": "Træning slettet",
 "Workout discarded": "Træning kasseret",
 "Workout name": "Træningsnavn",
 "Workout summary": "Træningsoversigt",
 "Yes, delete everything": "Ja, slet alt",
 "Your copy of this food": "Din kopi af denne fødevare",
 "Your experience": "Din erfaring",
 "Your food": "Din fødevare",
 "Your macros add up to about {n} kcal, which differs from your calorie target.": "Dine makroer giver cirka {n} kcal, hvilket afviger fra dit kalorimål.",
 "Your name": "Dit navn",
 "Your plan": "Din plan",
 "Your recipe": "Din opskrift",
 "Your records": "Dine rekorder",
 "Your workout history is never changed by moving or skipping.": "Din træningshistorik ændres aldrig, når du flytter eller springer over.",
 "You’re offline": "Du er offline",
 "You’re offline — barcode lookup needs a connection. You can still add it yourself.": "Du er offline — opslag på stregkode kræver forbindelse. Du kan stadig tilføje det selv.",
 "avg": "gns.",
 "avg per logged day": "gns. pr. logget dag",
 "calculated": "beregnet",
 "change day": "skift dag",
 "copy": "kopi",
 "days a week": "dage om ugen",
 "days ago": "dage siden",
 "days logged": "dage logget",
 "done": "færdig",
 "e.g. 1 slice": "fx 1 skive",
 "e.g. Overnight oats": "fx Overnight oats",
 "e.g. Push day": "fx Skubbedag",
 "e.g. Restaurant pasta": "fx Restaurantpasta",
 "editable": "kan redigeres",
 "entries": "poster",
 "est. 1RM": "est. 1RM",
 "estimate": "estimat",
 "estimated portion": "estimeret portion",
 "exercises": "øvelser",
 "food entries": "madposter",
 "last": "sidst",
 "made up to show the app": "opdigtet for at vise appen",
 "measured": "målt",
 "more": "mere",
 "my equipment": "mit udstyr",
 "needs a prepared weight": "kræver en færdig vægt",
 "next": "næste",
 "no RPE/RIR": "ingen RPE/RIR",
 "no calorie data": "ingen kaloriedata",
 "no data": "ingen data",
 "nothing logged": "intet logget",
 "of": "af",
 "of target": "af mål",
 "optional": "valgfrit",
 "per": "pr.",
 "per serving": "pr. portion",
 "portion": "portion",
 "protein": "protein",
 "records": "rekorder",
 "record": "rekord",
 "reps": "reps",
 "reps best": "reps bedst",
 "required": "påkrævet",
 "rest": "hvil",
 "rotation": "rotation",
 "routines": "programmer",
 "saved only on this device, stripped of location data, and not included in exports unless you choose.": "gemmes kun på denne enhed, uden placeringsdata, og medtages ikke i eksport, medmindre du vælger det.",
 "serving": "portion",
 "servings": "portioner",
 "sessions": "træninger",
 "sets": "sæt",
 "short": "mangler",
 "some items lack data": "nogle poster mangler data",
 "speech-to-text is performed by your browser (on Chrome this is a Google cloud service). Aven itself never records or stores audio; it only reads the microphone level to animate the sphere while you speak.": "tale-til-tekst udføres af din browser (i Chrome er det en Google-skytjeneste). Aven optager eller gemmer aldrig selv lyd; den læser kun mikrofonniveauet for at animere kuglen, mens du taler.",
 "suggested": "foreslået",
 "summed": "lagt sammen",
 "superset": "superset",
 "target": "mål",
 "this week": "denne uge",
 "today": "i dag",
 "total": "i alt",
 "volume": "volumen",
 "was": "var",
 "weekly split": "ugentlig split",
 "weigh-ins": "vejninger",
 "when on, the text you search is sent to Aven’s lookup server, which forwards it to Open Food Facts and USDA FoodData Central. Nothing else is sent. Turn it off in Food & water.": "når det er slået til, sendes din søgetekst til Avens opslagsserver, som videresender den til Open Food Facts og USDA FoodData Central. Intet andet sendes. Slå det fra under Mad og vand.",
 "wk": "uge",
 "workouts": "træninger",
 "{name} removed": "{name} fjernet",
 "{n} added — tap + to add more": "{n} tilføjet — tryk + for at tilføje flere",
 "{n} entries cleared": "{n} poster ryddet",
 "{n} sets aren’t checked off. They will not be saved.": "{n} sæt er ikke afkrydset. De gemmes ikke.",
 "{n} to resolve": "{n} at afklare",
 "{n}-week streak of hitting your target": "{n} uger i træk med målet nået",
 "“200 grams of skyr and a banana” — review, then confirm.": "“200 gram skyr og en banan” — gennemse, og bekræft så.",
 "“200 grams of skyr, one banana and 60 grams of oats”": "“200 gram skyr, en banan og 60 gram havregryn”",
 "“Bench press 80 kilos for 8, 8 and 6”": "“Bænkpres 80 kilo for 8, 8 og 6”",
 "“{u}” can’t be converted for this food (no known density or portion). Enter grams:": "“{u}” kan ikke omregnes for denne fødevare (ingen kendt densitet eller portion). Skriv gram:",
 "Core": "Mave",
 "Cardio": "Cardio",
 "Bench": "Bænk",
 "Machine": "Maskine",
 "Cable": "Kabel",
 "Band": "Elastik",
 "Other": "Andet",
 "Push": "Skub",
 "Hinge": "Hofteløft",
 "Lunge": "Udfald",
 "Carry": "Bær",
 "Isolation": "Isolation",
 "Run": "Løb",
 "Walk": "Gåtur",
 "Cycle": "Cykling",
 "Swim": "Svømning",
 "Hike": "Vandretur",
 "Mobility": "Mobilitet",
 "Warm-up": "Opvarmning",
 "Recovery": "Restitution",
 "Activity": "Aktivitet",
 "Motion: system": "Bevægelse: system",
 "Reduced motion": "Reduceret bevægelse",
 "Full motion": "Fuld bevægelse",
 "Fixed": "Fast",
 "Tuesday": "Tirsdag",
 "Full gym": "Fuldt fitnesscenter",
 "Barbells, machines, cables": "Stænger, maskiner, kabler",
 "Home with barbell": "Hjemme med stang",
 "Barbell, dumbbells, bench": "Stang, håndvægte, bænk",
 "Home with dumbbells": "Hjemme med håndvægte",
 "Dumbbells, kettlebell, bands": "Håndvægte, kettlebell, elastikker",
 "Bodyweight only": "Kun kropsvægt",
 "No equipment": "Intet udstyr",
 "Main": "Hoved",
 "Legs": "Ben",
 "Upper A": "Overkrop A",
 "Upper B": "Overkrop B",
 "Lower A": "Underkrop A",
 "Lower B": "Underkrop B",
 "Full body A": "Hele kroppen A",
 "Full body B": "Hele kroppen B",
 "Full body C": "Hele kroppen C"
};
