/** Danish strings. Keys are the English UI strings. Missing keys fall back to English (see scripts/i18n-keys.mjs --missing). */
export const da: Record<string, string> = {
 "Try saying": "Prøv at sige",
 "Time to train": "Tid til at træne",
 "That’s a lot — check the amount": "Det er meget — tjek mængden",
 "Logged 1 set": "Loggede 1 sæt",
 "Log 1 item": "Log 1 ting",
 "Log 1 exercise": "Log 1 øvelse",
 "exercise": "øvelse",
 "Add 1 exercise": "Tilføj 1 øvelse",
 "\"—\" means no data, not zero. \"≥\" means some entries had no value for it.": "\"—\" betyder ingen data, ikke nul. \"≥\" betyder, at nogle poster mangler en værdi.",
 "\"—\" means the source has no value — it is not counted as zero.": "\"—\" betyder, at kilden ikke har en værdi — den tælles ikke som nul.",
 "+ Warm-up": "+ Opvarmning",
 "12 weeks": "12 uger",
 "15 seconds less": "15 sekunder mindre",
 "15 seconds more": "15 sekunder mere",
 "4 weeks": "4 uger",
 "6 months": "6 måneder",
 "A bit of everything": "Lidt af det hele",
 "A new version of Aven is ready.": "En ny version af Aven er klar.",
 "A record beats your previous best for that exact measure. First-time exercises set a baseline, not a record. Tap an exercise to see the definitions.": "En rekord slår din tidligere bedste for præcis det mål. Første gang en øvelse logges, sætter den et udgangspunkt, ikke en rekord. Tryk på en øvelse for at se definitionerne.",
 "A routine is a list of exercises with planned sets and rep ranges. Build one, or set up a starter plan.": "Et program er en liste af øvelser med planlagte sæt og rep-intervaller. Lav et selv, eller start med en startplan.",
 "A simple, conventional template matched to your goal, experience and equipment — a place to start, not a prescription.": "En enkel, klassisk skabelon tilpasset dit mål, din erfaring og dit udstyr — et sted at starte, ikke en ordination.",
 "A web app can only notify you while Aven is open or installed and running in the background. Reliable scheduled reminders when the app is closed need a push server, which isn’t built yet. Rest-timer alerts (sound and vibration) work while you train.": "En webapp kan kun give dig besked, mens Aven er åben eller installeret og kører i baggrunden. Pålidelige påmindelser, når appen er lukket, kræver en push-server, som endnu ikke er bygget. Hviletimer-alarmer (lyd og vibration) virker, mens du træner.",
 "About Aven": "Om Aven",
 "Active workout": "Aktiv træning",
 "Activity is logged for your records. It is never added to your calorie targets.": "Aktivitet logges til dine optegnelser. Den lægges aldrig oven i dine kaloriemål.",
 "Activity logged": "Aktivitet logget",
 "Add": "Tilføj",
 "Add exercise": "Tilføj øvelse",
 "Add exercises": "Tilføj øvelser",
 "Add exercises, or dictate what you did.": "Tilføj øvelser, eller indtal, hvad du har lavet.",
 "Add food": "Tilføj mad",
 "Add ingredient — search foods": "Tilføj ingrediens — søg i fødevarer",
 "Add meal": "Tilføj måltid",
 "Add photo": "Tilføj foto",
 "Add portion": "Tilføj portion",
 "Add the exercises for this session.": "Tilføj øvelserne til denne træning.",
 "Add this product": "Tilføj dette produkt",
 "Add to": "Tilføj til",
 "Add to current workout": "Tilføj til nuværende træning",
 "Add to {meal}": "Tilføj til {meal}",
 "Add your first ingredient below.": "Tilføj din første ingrediens herunder.",
 "Add {n} exercises": "Tilføj {n} øvelser",
 "Added to workout": "Tilføjet til træningen",
 "Added to {meal}": "Tilføjet til {meal}",
 "Added {name}": "Tilføjede {name}",
 "Added {n} items to {meal}": "Tilføjede {n} ting til {meal}",
 "All": "Alle",
 "All optional. Leave a field empty to track it without a target. Aven never changes these for you — including after exercise.": "Alt er valgfrit. Lad et felt stå tomt for at spore uden mål. Aven ændrer aldrig disse for dig — heller ikke efter træning.",
 "Allow camera access in your browser settings, or type the number below.": "Giv adgang til kameraet i din browsers indstillinger, eller skriv nummeret herunder.",
 "Allow notifications": "Tillad notifikationer",
 "Also": "Desuden",
 "Amount": "Mængde",
 "Add, scan and photo under the ring.": "Tilføj, scan og foto under ringen.",
 "Choose what Today shows": "Vælg hvad I dag viser",
 "Colours": "Farver",
 "Customize Today": "Tilpas I dag",
 "I am {n} g short on protein today. What should I eat?": "Jeg mangler {n} g protein i dag. Hvad skal jeg spise?",
 "I am {n} kcal over today. Should I change anything tomorrow?": "Jeg er {n} kcal over i dag. Skal jeg ændre noget i morgen?",
 "I have {n} kcal left today. What should I eat?": "Jeg har {n} kcal tilbage i dag. Hvad skal jeg spise?",
 "It has been {n} days since I trained. What should I do today?": "Der er gået {n} dage siden jeg trænede. Hvad skal jeg lave i dag?",
 "Log 500 ml water": "Log 500 ml vand",
 "Log my weight": "Log min vægt",
 "Log your weight to see the trend.": "Log din vægt for at se tendensen.",
 "Log {food} again": "Log {food} igen",
 "Move my missed {routine} to tomorrow": "Flyt mit sprungne {routine} til i morgen",
 "No water logged today": "Intet vand logget i dag",
 "Nothing logged yet today": "Intet logget endnu i dag",
 "One-tap chips for what you eat often.": "Et tryk på det, du ofte spiser.",
 "Open progress": "Åbn fremgang",
 "Quick add buttons": "Hurtig-knapper",
 "Recent foods": "Seneste fødevarer",
 "Start my {routine} workout": "Start min {routine}-træning",
 "The water button here and the water card on the Food screen.": "Vandknappen her og vandkortet på Mad-skærmen.",
 "Week": "Uge",
 "Weight trend": "Vægttendens",
 "Workout running": "Træning i gang",
 "You missed {routine}": "Du missede {routine}",
 "Your training week as seven dots.": "Din træningsuge som syv prikker.",
 "Your weight and its trend line.": "Din vægt og dens tendenslinje.",
 "last {n} weigh-ins": "seneste {n} vejninger",
 "{n} days since you trained": "{n} dage siden du trænede",
 "{n} days since you weighed in": "{n} dage siden du vejede dig",
 "{n} g short on protein": "{n} g fra dit proteinmål",
 "{n} kcal left today": "{n} kcal tilbage i dag",
 "{n} kcal over today": "{n} kcal over i dag",
 "{routine} is planned today": "{routine} er planlagt i dag",
 "Added when set 1 reaches the top of the rep range": "Lægges på, når sæt 1 når toppen af rep-intervallet",
 "Weight jump": "Vægtspring",
 "+{inc} on every set — set 1 hit {max} reps last time": "+{inc} på alle sæt — sæt 1 nåede {max} reps sidst",
 "Same weight — one more rep per set": "Samme vægt — én rep mere pr. sæt",
 "Hold the weight — build set 1 back up to {min} reps": "Hold vægten — byg sæt 1 op til {min} reps igen",
 "Stalled — set 1 hasn’t improved in 3 sessions at {w}": "Gået i stå — sæt 1 er ikke blevet bedre i 3 træninger på {w}",
 "First time — pick a weight you can do {min}–{max} reps with": "Første gang — vælg en vægt du kan tage {min}–{max} reps med",
 "Appearance": "Udseende",
 "Arm": "Arm",
 "Assisted": "Assisteret",
 "Aven": "Aven",
 "Aven doesn’t prescribe targets. If you’re unsure, a dietitian or coach can help you choose.": "Aven foreskriver ikke mål. Er du i tvivl, kan en diætist eller træner hjælpe dig med at vælge.",
 "Aven has no account and no analytics. Your workouts, meals, weight and photos are stored in this browser’s local storage and IndexedDB.": "Aven har ingen konto og ingen analytics. Dine træninger, måltider, vægt og fotos gemmes i denne browsers lokale lager og IndexedDB.",
 "Back": "Tilbage",
 "Backup downloaded": "Sikkerhedskopi hentet",
 "Backup restored": "Sikkerhedskopi gendannet",
 "Barbell": "Stang",
 "Barcode (optional)": "Stregkode (valgfri)",
 "Barcode lookup isn’t available right now. You can add this product yourself.": "Opslag på stregkode er ikke tilgængeligt lige nu. Du kan selv tilføje produktet.",
 "Barcode number": "Stregkodenummer",
 "Best set volume": "Bedste sæt-volumen",
 "Biceps": "Biceps",
 "Blank fields are stored as unknown, not zero.": "Tomme felter gemmes som ukendt, ikke nul.",
 "Body measurements": "Kropsmål",
 "Bodyweight": "Kropsvægt",
 "Brand (optional)": "Mærke (valgfri)",
 "Breakfast": "Morgenmad",
 "Build a routine": "Lav et program",
 "Build muscle": "Opbyg muskler",
 "Build routine": "Lav program",
 "Bundled foods are approximate reference values. Online results come from Open Food Facts (© contributors, ODbL — open database licence) and USDA FoodData Central (public domain, CC0).": "Medfølgende fødevarer er omtrentlige referenceværdier. Online-resultater kommer fra Open Food Facts (© bidragydere, ODbL — åben databaselicens) og USDA FoodData Central (almindeligt tilgængelig, CC0).",
 "Bundled foods, your saved foods and manual entry all still work.": "Medfølgende fødevarer, dine gemte fødevarer og manuel indtastning virker stadig.",
 "Bundled reference values are typical averages. Correct them by making your own copy.": "Medfølgende referenceværdier er typiske gennemsnit. Ret dem ved at lave din egen kopi.",
 "Calories": "Kalorier",
 "Calories and macros are optional — set them any time.": "Kalorier og makroer er valgfrie — sæt dem når som helst.",
 "Calories and macros differ by more than 25% (4/4/9 kcal per g). Double-check — alcohol and fibre can explain some of it.": "Kalorier og makroer afviger med mere end 25 % (4/4/9 kcal pr. g). Tjek igen — alkohol og fibre kan forklare noget af det.",
 "Calories and macros differ by more than 25%. Check the label — alcohol and fibre can explain some of it.": "Kalorier og makroer afviger med mere end 25 %. Tjek etiketten — alkohol og fibre kan forklare noget af det.",
 "Calories per day": "Kalorier pr. dag",
 "Calories, macros, water — optional": "Kalorier, makroer, vand — valgfrit",
 "Calves": "Lægge",
 "Camera permission was denied.": "Adgang til kameraet blev afvist.",
 "Camera scanning isn’t supported in this browser.": "Kameraskanning understøttes ikke i denne browser.",
 "Cancel": "Annuller",
 "Carbs": "Kulhydrat",
 "Change": "Skift",
 "Changing a food never rewrites entries you already logged.": "Ændringer af en fødevare omskriver aldrig poster, du allerede har logget.",
 "Check and confirm": "Tjek og bekræft",
 "Chest": "Bryst",
 "Choose": "Vælg",
 "Choose file": "Vælg fil",
 "Clear": "Ryd",
 "Clear day": "Ryd dagen",
 "Clear meal": "Ryd måltid",
 "Clear nutrition targets": "Ryd ernæringsmål",
 "Clearing browser data removes everything. Export a backup first (Data & backup).": "Rydder du browserdata, forsvinder alt. Lav først en sikkerhedskopi (Data og backup).",
 "Close": "Luk",
 "Combine ingredients once, then log servings in two taps.": "Saml ingredienser én gang, og log derefter portioner med to tryk.",
 "Complete set": "Afslut sæt",
 "Confirm": "Bekræft",
 "Continue": "Fortsæt",
 "Cooked": "Tilberedt",
 "Copied {n} entries to {day}": "Kopierede {n} poster til {day}",
 "Copy": "Kopiér",
 "Copy day to…": "Kopiér dag til…",
 "Copy meal to…": "Kopiér måltid til…",
 "Copy to day": "Kopiér til dag",
 "Copy to {day}": "Kopiér til {day}",
 "Copy to…": "Kopiér til…",
 "Correct → my copy": "Ret → min kopi",
 "Couldn’t listen": "Kunne ikke lytte",
 "Couldn’t save that photo": "Kunne ikke gemme fotoet",
 "Couldn’t save to this browser’s storage. Export a backup now.": "Kunne ikke gemme i browserens lager. Lav en sikkerhedskopi nu.",
 "Couldn’t start the camera.": "Kunne ikke starte kameraet.",
 "Create a routine first, then schedule it here.": "Lav først et program, og planlæg det så her.",
 "Create a starter plan": "Opret en startplan",
 "Create custom exercise": "Opret egen øvelse",
 "Create exercise": "Opret øvelse",
 "Create food": "Opret fødevare",
 "Create it once and it is yours to reuse.": "Opret den én gang, så kan du bruge den igen.",
 "Create it once and it stays in your library.": "Opret den én gang, så bliver den i dit bibliotek.",
 "Create your own foods and recipes — they are kept on this device.": "Opret dine egne fødevarer og opskrifter — de gemmes på denne enhed.",
 "Create “{q}”": "Opret “{q}”",
 "Cues, seat height, how it felt…": "Tips, sædehøjde, hvordan det føltes…",
 "Custom": "Egen",
 "Custom exercise": "Egen øvelse",
 "Daily goal": "Dagligt mål",
 "Dansk": "Dansk",
 "Dark": "Mørk",
 "Data & backup": "Data og backup",
 "Date": "Dato",
 "Dates and numbers follow your language. Distance and measurements follow your weight unit; change them individually in Settings.": "Datoer og tal følger dit sprog. Afstand og mål følger din vægtenhed; ændr dem enkeltvis i Indstillinger.",
 "Day": "Dag",
 "Day options": "Dagsvalg",
 "Days with nothing logged are faded and left out of averages — they are not zero-calorie days.": "Dage uden logning er toned ned og holdes uden for gennemsnit — de er ikke dage med nul kalorier.",
 "Default rest between sets": "Standardhvile mellem sæt",
 "Delete": "Slet",
 "Delete all data": "Slet alle data",
 "Delete entry": "Slet post",
 "Delete everything": "Slet alt",
 "Delete recipe": "Slet opskrift",
 "Delete routine": "Slet program",
 "Delete set": "Slet sæt",
 "Deleted": "Slettet",
 "Demo data": "Demodata",
 "Demo data loaded": "Demodata indlæst",
 "Demo data loaded — remove it any time in Settings": "Demodata indlæst — fjern dem når som helst i Indstillinger",
 "Demo data removed": "Demodata fjernet",
 "Density": "Densitet",
 "Density (g per ml) — only if you know it": "Densitet (g pr. ml) — kun hvis du kender den",
 "Details": "Detaljer",
 "Diagram: front and back. Orange = main muscle, tint = helpers. No video demonstration is included.": "Diagram: forfra og bagfra. Orange = hovedmuskel, nuance = hjælpemuskler. Ingen videodemonstration er medtaget.",
 "Dictate": "Indtal",
 "Dictate sets": "Indtal sæt",
 "Dictation": "Diktering",
 "Didn’t catch anything. Tap the sphere to try again, or type it.": "Jeg hørte ikke noget. Tryk på kuglen for at prøve igen, eller skriv det.",
 "Dinner": "Aftensmad",
 "Discard workout": "Kassér træning",
 "Discard workout?": "Kassér træning?",
 "Dismiss": "Afvis",
 "Distance": "Afstand",
 "Do it today": "Gør det i dag",
 "Done": "Færdig",
 "Done for today": "Færdig for i dag",
 "Done speaking": "Færdig med at tale",
 "Download backup": "Hent sikkerhedskopi",
 "Dry": "Tør",
 "Dumbbell": "Håndvægt",
 "Duplicate": "Dupliker",
 "Duplicated": "Duplikeret",
 "Duration": "Varighed",
 "Eaten": "Spist",
 "Eaten today": "Spist i dag",
 "Edit": "Rediger",
 "Edit entry": "Rediger post",
 "Edit exercise": "Rediger øvelse",
 "Edit food": "Rediger fødevare",
 "Edit quick amounts": "Rediger hurtige mængder",
 "Edit recipe": "Rediger opskrift",
 "Edit routine": "Rediger program",
 "Edit text": "Rediger tekst",
 "Edits change this record only. Personal-record flags are not recalculated.": "Rettelser ændrer kun denne optegnelse. Rekordmærker genberegnes ikke.",
 "Effort (RPE/RIR) can be turned on in Settings.": "Anstrengelse (RPE/RIR) kan slås til i Indstillinger.",
 "Effort tracking": "Anstrengelsessporing",
 "Empty": "Tom",
 "Empty session": "Tom træning",
 "Endurance": "Udholdenhed",
 "English": "English",
 "Enter reps first": "Skriv reps først",
 "Entries moved to {meal}": "Poster flyttet til {meal}",
 "Epley: weight × (1 + reps ÷ 30), sets of up to 12 reps — an estimate, not a tested max": "Epley: vægt × (1 + reps ÷ 30), sæt på op til 12 reps — et estimat, ikke et testet maks",
 "Equipment": "Udstyr",
 "Estimated 1RM": "Estimeret 1RM",
 "Estimated 1RM over time": "Estimeret 1RM over tid",
 "Everything stays on this device.": "Alt bliver på denne enhed.",
 "Exercise": "Øvelse",
 "Exercise details": "Øvelsesdetaljer",
 "Exercise note": "Øvelsesnote",
 "Exercise options": "Øvelsesvalg",
 "Exercise removed": "Øvelse fjernet",
 "Exercise trends": "Øvelsestendenser",
 "Exercises": "Øvelser",
 "Experienced": "Erfaren",
 "Explore with demo data instead": "Udforsk med demodata i stedet",
 "Export backup": "Eksportér sikkerhedskopi",
 "Export, import, delete": "Eksportér, importér, slet",
 "Fat": "Fedt",
 "Favourite": "Favorit",
 "Favourites": "Favoritter",
 "Fibre": "Fibre",
 "Finish": "Afslut",
 "Finish and save {n} sets": "Afslut og gem {n} sæt",
 "Finish workout": "Afslut træning",
 "Finish workout?": "Afslut træning?",
 "Finish your current workout first": "Afslut først din nuværende træning",
 "Finished workouts and activities land here, and stay editable.": "Afsluttede træninger og aktiviteter havner her og kan stadig redigeres.",
 "Fixed weekdays": "Faste ugedage",
 "Flexible rotation": "Fleksibel rotation",
 "Food": "Mad",
 "Food & water": "Mad og vand",
 "Food data": "Fødevaredata",
 "Food lookup": "Fødevareopslag",
 "Food updated — past entries keep their old values": "Fødevare opdateret — tidligere poster beholder deres gamle værdier",
 "Foods you log will show up here for one-tap repeats.": "Fødevarer, du logger, dukker op her, så du kan gentage dem med ét tryk.",
 "Forearms": "Underarme",
 "Full": "Fuld",
 "General fitness": "Generel fitness",
 "Get stronger": "Bliv stærkere",
 "Getting started": "Kom i gang",
 "Glutes": "Baller",
 "Go": "Kør",
 "Go to day": "Gå til dag",
 "Goal": "Mål",
 "Good afternoon": "God eftermiddag",
 "Good evening": "God aften",
 "Good morning": "God morgen",
 "Grams (solids)": "Gram (fast føde)",
 "Grams are hidden: this food has no known density.": "Gram er skjult: denne fødevare har ingen kendt densitet.",
 "Hamstrings": "Baglår",
 "Haptic feedback": "Haptisk feedback",
 "Haptics work on devices and browsers that support vibration (mostly Android).": "Haptik virker på enheder og browsere med vibration (mest Android).",
 "Heavier lifts, lower reps": "Tungere løft, færre reps",
 "Heaviest set": "Tungeste sæt",
 "Heaviest weight lifted for 1+ reps": "Tungeste vægt løftet for 1+ reps",
 "Higher reps, shorter rests": "Flere reps, kortere hvil",
 "Highest reps in one working set": "Flest reps i ét arbejdssæt",
 "Hips": "Hofter",
 "History": "Historik",
 "Hit {n} sessions in a week to start a streak.": "Nå {n} træninger på en uge for at starte en stime.",
 "Honest limits": "Ærlige begrænsninger",
 "How did it feel?": "Hvordan føltes det?",
 "How is it logged?": "Hvordan logges den?",
 "How it’s going": "Sådan går det",
 "How much?": "Hvor meget?",
 "How to": "Sådan gør du",
 "Hunger, cravings, eating out…": "Sult, trang, spise ude…",
 "I couldn’t find any foods in that. Try “150 grams of rice and a banana”.": "Jeg kunne ikke finde nogen fødevarer i det. Prøv “150 gram ris og en banan”.",
 "Import backup": "Importér sikkerhedskopi",
 "In progress": "I gang",
 "Include photos": "Medtag fotos",
 "Include progress photos (larger file)": "Medtag fremgangsfotos (større fil)",
 "Ingredients": "Ingredienser",
 "Instructions (one step per line, optional)": "Instruktioner (ét trin pr. linje, valgfrit)",
 "Into meal": "Ind i måltid",
 "Just this day": "Kun denne dag",
 "Keep": "Behold",
 "Keep training": "Fortsæt træningen",
 "Kettlebell": "Kettlebell",
 "Label": "Betegnelse",
 "Language": "Sprog",
 "Last": "Sidst",
 "Late night": "Sen aften",
 "Late-night meals before this hour count toward the previous day.": "Sene måltider før dette tidspunkt tæller med til den forrige dag.",
 "Less": "Mindre",
 "Let’s set up Aven.": "Lad os sætte Aven op.",
 "Library": "Bibliotek",
 "Light": "Lys",
 "Listening": "Lytter",
 "Listening (no level meter)": "Lytter (uden niveaumåler)",
 "Load demo data": "Indlæs demodata",
 "Load × reps": "Vægt × reps",
 "Log": "Log",
 "Log a workout, a meal or your weight and this page fills in. Charts only show what you have actually recorded.": "Log en træning, et måltid eller din vægt, så fyldes siden ud. Diagrammer viser kun det, du faktisk har registreret.",
 "Log activity": "Log aktivitet",
 "Log as you go, or build a routine and let Aven line up your week.": "Log undervejs, eller lav et program og lad Aven lægge din uge.",
 "Log calories and macros without picking a food.": "Log kalorier og makroer uden at vælge en fødevare.",
 "Log cardio / recovery": "Log cardio / restitution",
 "Log cardio or recovery": "Log cardio eller restitution",
 "Log food": "Log mad",
 "Log on day": "Log på dag",
 "Log your weight": "Log din vægt",
 "Log your weight to see a trend. Weigh-ins are noisy — the trend line smooths them.": "Log din vægt for at se en tendens. Vejninger svinger — tendenslinjen udjævner dem.",
 "Log {n} exercises": "Log {n} øvelser",
 "Log {n} items": "Log {n} ting",
 "Logged": "Logget",
 "Logged {n} sets": "Loggede {n} sæt",
 "Longest distance": "Længste afstand",
 "Longest hold": "Længste hold",
 "Longest single working set": "Længste enkelte arbejdssæt",
 "Look up": "Slå op",
 "Lookup is rate-limited — try again shortly": "Opslag er begrænset — prøv igen om lidt",
 "Lookup is rate-limited — try again shortly.": "Opslag er begrænset — prøv igen om lidt.",
 "Lose fat": "Tab fedt",
 "Lunch": "Frokost",
 "Made-up workouts, meals and weigh-ins so you can explore every screen. Clearly labelled, removable.": "Opdigtede træninger, måltider og vejninger, så du kan udforske alle skærme. Tydeligt mærket og kan fjernes.",
 "Make warm-up": "Gør til opvarmning",
 "Make working set": "Gør til arbejdssæt",
 "Mark set not done": "Markér sæt som ikke færdigt",
 "Matched": "Matchet",
 "Meal": "Måltid",
 "Meal options": "Måltidsvalg",
 "Meals": "Måltider",
 "Meals, quick amounts, lookup": "Måltider, hurtige mængder, opslag",
 "Measured in": "Måles i",
 "Measurement": "Mål",
 "Measurements": "Mål",
 "Microphone or speech permission was denied. You can allow it in your browser settings, or type instead.": "Adgang til mikrofon eller tale blev afvist. Du kan tillade det i browserens indstillinger, eller skrive i stedet.",
 "Microphone unavailable": "Mikrofon utilgængelig",
 "Millilitres (drinks)": "Milliliter (drikke)",
 "Millilitres are hidden: this food has no known density, so ml ≠ g can’t be assumed.": "Milliliter er skjult: denne fødevare har ingen kendt densitet, så ml ≠ g kan ikke antages.",
 "Min": "Min",
 "Minimise workout": "Minimér træning",
 "Minutes": "Minutter",
 "Missed": "Overset",
 "Missed workouts": "Oversete træninger",
 "Monday": "Mandag",
 "More": "Mere",
 "More filters": "Flere filtre",
 "More nutrients": "Flere næringsstoffer",
 "More nutrients, portions and details": "Flere næringsstoffer, portioner og detaljer",
 "Most reps": "Flest reps",
 "Most reps in a set": "Flest reps i et sæt",
 "Motion": "Bevægelse",
 "Move down": "Flyt ned",
 "Move them or skip — your history is never changed.": "Flyt dem eller spring over — din historik ændres aldrig.",
 "Move to…": "Flyt til…",
 "Move up": "Flyt op",
 "Moved {name} to {day}": "Flyttede {name} til {day}",
 "Movement": "Bevægelse",
 "Muscles (first tapped = primary)": "Muskler (første tryk = primær)",
 "My foods": "Mine fødevarer",
 "Name": "Navn",
 "Neck": "Nakke",
 "Needed to convert between grams and millilitres. Leave blank if unsure.": "Bruges til at omregne mellem gram og milliliter. Lad feltet stå tomt, hvis du er i tvivl.",
 "New": "Ny",
 "New day starts at": "Ny dag starter kl.",
 "New exercise": "Ny øvelse",
 "New food": "Ny fødevare",
 "New meal": "Nyt måltid",
 "New recipe": "Ny opskrift",
 "New routine": "Nyt program",
 "Next day": "Næste dag",
 "Next month": "Næste måned",
 "Nice work": "Flot arbejde",
 "No cloud sync or accounts. No photo-based food estimation. The Coach only advises and never changes your data. Background reminders need a push server.": "Ingen skysynkronisering eller konti. Ingen fotobaseret madestimering. Coachen rådgiver kun og ændrer aldrig dine data. Baggrundspåmindelser kræver en push-server.",
 "No entries for this day": "Ingen poster for denne dag",
 "No exercise found": "Ingen øvelse fundet",
 "No exercise matched “{q}”": "Ingen øvelse matchede “{q}”",
 "No favourites yet": "Ingen favoritter endnu",
 "No fixed days. Aven lines up the next routine in the order below and moves on when you finish it.": "Ingen faste dage. Aven stiller det næste program op i rækkefølgen herunder og går videre, når du er færdig.",
 "No history yet": "Ingen historik endnu",
 "No instructions yet.": "Ingen instruktioner endnu.",
 "No match for “{q}”": "Ingen match for “{q}”",
 "No microphone was found or it is in use by another app.": "Der blev ikke fundet nogen mikrofon, eller den bruges af en anden app.",
 "No new records this time. First-time exercises set a baseline — records need something to beat.": "Ingen nye rekorder denne gang. Øvelser, du logger første gang, sætter et udgangspunkt — rekorder skal have noget at slå.",
 "No personal foods yet": "Ingen egne fødevarer endnu",
 "No photos yet": "Ingen fotos endnu",
 "No product found for {c}. You can add it yourself.": "Intet produkt fundet for {c}. Du kan tilføje det selv.",
 "No recipes yet": "Ingen opskrifter endnu",
 "No routines yet": "Ingen programmer endnu",
 "No saved meals yet": "Ingen gemte måltider endnu",
 "No sets found. Try “80 kilos for 8”.": "Ingen sæt fundet. Prøv “80 kilo for 8”.",
 "No workout is running — confirming will start one.": "Ingen træning kører — bekræfter du, startes en.",
 "Not found": "Ikke fundet",
 "Not this food?": "Ikke denne fødevare?",
 "Note": "Note",
 "Notes": "Noter",
 "Nothing extra online.": "Intet ekstra online.",
 "Nothing has been logged yet. You can undo this right after.": "Der er ikke logget noget endnu. Du kan fortryde lige bagefter.",
 "Nothing is recorded or sent anywhere.": "Intet optages eller sendes nogen steder hen.",
 "Nothing logged yet": "Intet logget endnu",
 "Nothing logged yet.": "Intet logget endnu.",
 "Nothing planned today": "Intet planlagt i dag",
 "Nothing to add": "Intet at tilføje",
 "Nothing to chart yet": "Intet at vise endnu",
 "Nothing yet today.": "Intet endnu i dag.",
 "Notifications are allowed. Aven will remind you at that time on planned training days while it is running.": "Notifikationer er tilladt. Aven minder dig på det tidspunkt på planlagte træningsdage, mens den kører.",
 "Notifications are blocked in your browser. You’ll see an in-app nudge on Today instead.": "Notifikationer er blokeret i din browser. Du får i stedet et skub i appen under I dag.",
 "Numbers and dates follow your language. Decimal commas and points both work when typing. Values are stored in metric and converted for display.": "Tal og datoer følger dit sprog. Både decimalkomma og -punktum virker, når du skriver. Værdier gemmes metrisk og omregnes ved visning.",
 "Nutrition": "Ernæring",
 "Nutrition targets": "Ernæringsmål",
 "Nutrition values are…": "Næringsværdier er…",
 "Off": "Fra",
 "One JSON file with everything: workouts, food, plans, settings.": "Én JSON-fil med det hele: træninger, mad, planer, indstillinger.",
 "One number starts your trend.": "Ét tal starter din tendens.",
 "One weigh-in so far. A second one starts the trend line.": "Kun én vejning indtil videre. En anden starter tendenslinjen.",
 "One-off change. Your repeating plan stays the same.": "Engangsændring. Din gentagne plan forbliver den samme.",
 "Online food lookup": "Online fødevareopslag",
 "Online lookup": "Online opslag",
 "Online lookup isn’t available": "Online opslag er ikke tilgængeligt",
 "Only available on an empty app, so it can’t mix with your real records.": "Kun tilgængelig i en tom app, så det ikke blandes med dine rigtige data.",
 "Only what my equipment allows": "Kun det mit udstyr tillader",
 "Open a meal in your diary, tap ⋯ and choose “Save as meal”.": "Åbn et måltid i din dagbog, tryk på ⋯ og vælg “Gem som måltid”.",
 "Open log": "Åbn log",
 "Optional": "Valgfrit",
 "Optional. Skip to simply track what you eat; set targets whenever you like.": "Valgfrit. Spring over for blot at spore, hvad du spiser; sæt mål, når du har lyst.",
 "Optional. Stored on this device.": "Valgfrit. Gemmes på denne enhed.",
 "Options": "Valg",
 "Over target": "Over mål",
 "Pause": "Pause",
 "Paused": "På pause",
 "Paused — the clock is stopped. Logging a set resumes it.": "På pause — uret er stoppet. Logger du et sæt, genoptages det.",
 "Per serving": "Pr. portion",
 "Permanently erases all Aven data and photos from this device.": "Sletter permanent alle Aven-data og fotos fra denne enhed.",
 "Personal food": "Egen fødevare",
 "Personal records": "Personlige rekorder",
 "Photo": "Foto",
 "Photo deleted": "Foto slettet",
 "Photo saved privately on this device": "Foto gemt privat på denne enhed",
 "Photos": "Fotos",
 "Pick": "Vælg",
 "Pick a day": "Vælg en dag",
 "Pick a routine for each training day. Missed days can be moved without touching your history.": "Vælg et program til hver træningsdag. Oversete dage kan flyttes uden at røre din historik.",
 "Pick date": "Vælg dato",
 "Pick the days you usually train. Flexible rotations are available later.": "Vælg de dage, du plejer at træne. Fleksible rotationer kan vælges senere.",
 "Pick training days first": "Vælg først træningsdage",
 "Plan": "Plan",
 "Planned sets and rep ranges are targets. What you actually do is saved separately in each workout.": "Planlagte sæt og rep-intervaller er mål. Det, du rent faktisk gør, gemmes separat i hver træning.",
 "Planned vs done": "Planlagt vs. gjort",
 "Planning ahead — entries save to this day.": "Planlægger frem — poster gemmes på denne dag.",
 "Portion size is a typical estimate — adjust if you know the weight.": "Portionsstørrelsen er et typisk skøn — ret den, hvis du kender vægten.",
 "Portions": "Portioner",
 "Prepared as": "Tilberedt som",
 "Prepared weight": "Færdig vægt",
 "Prev": "Sidst",
 "Previous day": "Forrige dag",
 "Previous month": "Forrige måned",
 "Privacy": "Privatliv",
 "Private by design: photos stay on this device, are shrunk and stripped of location data, and are never uploaded or included in exports unless you choose.": "Privat fra start: fotos bliver på denne enhed, formindskes og mister placeringsdata, og de uploades aldrig eller medtages i eksport, medmindre du vælger det.",
 "Product data comes from Open Food Facts when the lookup server is reachable; your saved foods are checked first.": "Produktdata kommer fra Open Food Facts, når opslagsserveren kan nås; dine gemte fødevarer tjekkes først.",
 "Progress": "Fremgang",
 "Progress photo": "Fremgangsfoto",
 "Progress photos": "Fremgangsfotos",
 "Protein": "Protein",
 "Protein per day": "Protein pr. dag",
 "Pull": "Træk",
 "Quads": "Forlår",
 "Quick add": "Hurtig tilføjelse",
 "Quick amount": "Hurtig mængde",
 "Quick amounts (ml)": "Hurtige mængder (ml)",
 "Quick entry": "Hurtig post",
 "Quick entry added": "Hurtig post tilføjet",
 "RIR": "RIR",
 "RPE": "RPE",
 "RPE = how hard (1–10). RIR = reps left in the tank. Adds a column to each set.": "RPE = hvor hårdt (1–10). RIR = reps tilbage i tanken. Tilføjer en kolonne til hvert sæt.",
 "Raw": "Rå",
 "Raw and cooked weights are not interchangeable — cooking changes water content.": "Rå og tilberedte vægte kan ikke byttes om — tilberedning ændrer vandindholdet.",
 "Ready to restore": "Klar til gendannelse",
 "Ready.": "Klar.",
 "Recent": "Seneste",
 "Recent activity": "Seneste aktivitet",
 "Recent records": "Seneste rekorder",
 "Recent sessions": "Seneste træninger",
 "Recipe": "Opskrift",
 "Recipe saved — past entries are unchanged": "Opskrift gemt — tidligere poster er uændrede",
 "Recipes": "Opskrifter",
 "Redo setup": "Gentag opsætning",
 "Reduced": "Reduceret",
 "Reduced motion removes springs, slides and the sphere’s movement. Everything stays usable.": "Reduceret bevægelse fjerner fjedring, glidninger og kuglens bevægelse. Alt forbliver brugbart.",
 "Reference (approximate)": "Reference (omtrentlig)",
 "Remaining": "Tilbage",
 "Remembered": "Husket",
 "Reminders": "Påmindelser",
 "Remove": "Fjern",
 "Remove demo data": "Fjern demodata",
 "Remove exercise": "Fjern øvelse",
 "Remove favourite": "Fjern favorit",
 "Remove set": "Fjern sæt",
 "Removed": "Fjernet",
 "Rename, add or remove meals. Removing a meal keeps its entries, which move to the first meal.": "Omdøb, tilføj eller fjern måltider. Fjerner du et måltid, flyttes posterne til det første måltid.",
 "Rep range": "Rep-interval",
 "Repeat": "Gentag",
 "Repeating plan": "Gentagen plan",
 "Replace exercise": "Udskift øvelse",
 "Replace my data": "Erstat mine data",
 "Replaces everything on this device. You can undo right after.": "Erstatter alt på denne enhed. Du kan fortryde lige bagefter.",
 "Reps": "Reps",
 "Reschedule": "Omplanlæg",
 "Rescheduled": "Omplanlagt",
 "Rest": "Hvil",
 "Rest (seconds)": "Hvil (sekunder)",
 "Rest after a set": "Hvil efter et sæt",
 "Rest day": "Hviledag",
 "Rest over": "Hvilen er slut",
 "Rest-timer sound": "Lyd ved hviletimer",
 "Resume": "Genoptag",
 "Resume current": "Genoptag nuværende",
 "Resume workout": "Genoptag træning",
 "Reuse these foods in one tap": "Genbrug disse fødevarer med ét tryk",
 "Review": "Gennemse",
 "Routine": "Program",
 "Routine deleted": "Program slettet",
 "Routine saved": "Program gemt",
 "Routines": "Programmer",
 "Runs, walks, mobility, warm-ups — with duration and distance": "Løb, gåture, mobilitet, opvarmning — med varighed og afstand",
 "Same main muscle and movement; equipment you have comes first.": "Samme hovedmuskel og bevægelse; udstyr, du har, kommer først.",
 "Saturated fat": "Mættet fedt",
 "Save": "Gem",
 "Save activity": "Gem aktivitet",
 "Save as meal": "Gem som måltid",
 "Save as routine": "Gem som program",
 "Save changes": "Gem ændringer",
 "Save exercise": "Gem øvelse",
 "Save food": "Gem fødevare",
 "Save my copy": "Gem min kopi",
 "Save recipe": "Gem opskrift",
 "Save routine": "Gem program",
 "Saved": "Gemt",
 "Saved as routine": "Gemt som program",
 "Saved automatically.": "Gemmes automatisk.",
 "Saved changes": "Ændringer gemt",
 "Saved meals": "Gemte måltider",
 "Saved “{name}”": "Gemte “{name}”",
 "Say what you ate": "Sig, hvad du har spist",
 "Scan": "Scan",
 "Scan barcode": "Scan stregkode",
 "Schedule": "Planlæg",
 "Search Open Food Facts and USDA through Aven’s server. Off = bundled and personal foods only.": "Søg i Open Food Facts og USDA via Avens server. Fra = kun medfølgende og egne fødevarer.",
 "Search exercises": "Søg øvelser",
 "Search foods": "Søg fødevarer",
 "Search foods and brands": "Søg fødevarer og mærker",
 "Search something else": "Søg efter noget andet",
 "Search, scan, dictate or copy a meal. Logging a repeat takes two taps.": "Søg, scan, indtal eller kopiér et måltid. At logge en gentagelse tager to tryk.",
 "Searching Open Food Facts and USDA…": "Søger i Open Food Facts og USDA…",
 "Seconds": "Sekunder",
 "Select exercises": "Vælg øvelser",
 "Serving size": "Portionsstørrelse",
 "Servings": "Portioner",
 "Session note": "Træningsnote",
 "Sessions": "Træninger",
 "Sessions per week": "Træninger pr. uge",
 "Set": "Sæt",
 "Set deleted": "Sæt slettet",
 "Set options": "Sætvalg",
 "Set removed": "Sæt fjernet",
 "Set targets": "Sæt mål",
 "Set your targets": "Sæt dine mål",
 "Sets": "Sæt",
 "Settings": "Indstillinger",
 "Setup": "Opsætning",
 "Shoulders": "Skuldre",
 "Show as table": "Vis som tabel",
 "Show chart": "Vis diagram",
 "Six quick questions. Skip any of them — you can change everything later.": "Seks hurtige spørgsmål. Spring over, hvad du vil — du kan ændre alt senere.",
 "Skip": "Spring over",
 "Skip all": "Spring alt over",
 "Skip it": "Spring over",
 "Skipped": "Sprunget over",
 "Sleep, energy, niggles…": "Søvn, energi, småskavanker…",
 "Smallest weight jump": "Mindste vægtspring",
 "Snacks": "Snacks",
 "Sodium": "Natrium",
 "Some": "Lidt",
 "Some ingredients are in ml with no known density — enter the prepared weight so serving sizes can be computed.": "Nogle ingredienser er i ml uden kendt densitet — skriv den færdige vægt, så portionsstørrelser kan beregnes.",
 "Speak instead": "Tal i stedet",
 "Speech recognition couldn’t start.": "Talegenkendelsen kunne ikke starte.",
 "Speech recognition isn’t available in this browser. Type it, or use your keyboard’s microphone key.": "Talegenkendelse er ikke tilgængelig i denne browser. Skriv det, eller brug mikrofontasten på dit tastatur.",
 "Speech recognition stopped unexpectedly.": "Talegenkendelsen stoppede uventet.",
 "Speech-to-text is done by your browser’s speech service (often a cloud service). Audio is never stored by Aven.": "Tale-til-tekst udføres af din browsers talefunktion (ofte en skytjeneste). Aven gemmer aldrig lyd.",
 "Squat": "Squat",
 "Start": "Start",
 "Start again": "Start igen",
 "Start listening": "Begynd at lytte",
 "Start typing to find food": "Begynd at skrive for at finde mad",
 "Start workout": "Start træning",
 "Start your first session": "Start din første træning",
 "Starter plan": "Startplan",
 "Starter plan created — edit it in Train": "Startplan oprettet — rediger den under Træn",
 "Starting camera…": "Starter kamera…",
 "Starting the microphone…": "Starter mikrofonen…",
 "Stop and review": "Stop og gennemse",
 "Storage is full — export a backup and free space.": "Lageret er fuldt — eksportér en sikkerhedskopi og frigør plads.",
 "Substitutions": "Alternativer",
 "Sugars": "Sukkerarter",
 "Suggested substitutes": "Foreslåede alternativer",
 "Sunday": "Søndag",
 "Superset": "Superset",
 "Superset with next": "Superset med næste",
 "System": "System",
 "Tap the sphere and speak": "Tryk på kuglen og tal",
 "Tap the star on any food to keep it close.": "Tryk på stjernen ved en fødevare for at have den ved hånden.",
 "Target sessions per week": "Mål for træninger pr. uge",
 "Targets": "Mål",
 "Targets set to {w} {u}": "Mål sat til {w} {u}",
 "That backup is from a newer version of Aven.": "Den sikkerhedskopi er fra en nyere version af Aven.",
 "That file isn’t a valid Aven backup.": "Den fil er ikke en gyldig Aven-sikkerhedskopi.",
 "The browser’s speech service isn’t reachable (it needs a connection). Type instead — nothing was recorded.": "Browserens talefunktion kan ikke nås (den kræver forbindelse). Skriv i stedet — intet blev optaget.",
 "The original stays untouched; yours is used from now on.": "Originalen forbliver uændret; din bruges fremover.",
 "Theme": "Tema",
 "Thigh": "Lår",
 "This browser doesn’t support notifications. You’ll see an in-app nudge on Today instead.": "Denne browser understøtter ikke notifikationer. Du får i stedet et skub i appen under I dag.",
 "This portion": "Denne portion",
 "This week": "Denne uge",
 "Time": "Tid",
 "Today": "I dag",
 "Today’s workout": "Dagens træning",
 "Tomorrow": "I morgen",
 "Train": "Træn",
 "Train again": "Træn igen",
 "Train anyway, or pick one of your routines.": "Træn alligevel, eller vælg et af dine programmer.",
 "Training": "Træning",
 "Training consistency": "Træningskonsistens",
 "Training plus food awareness": "Træning plus madbevidsthed",
 "Training, food and progress in one place.": "Træning, mad og fremgang ét sted.",
 "Training-day reminder": "Påmindelse på træningsdage",
 "Trend": "Tendens",
 "Trend (estimate)": "Tendens (estimat)",
 "Trend rate needs 7+ days of data": "Tendenshastighed kræver 7+ dages data",
 "Triceps": "Triceps",
 "Try {w} {u} — all sets reached {reps} reps last time. Tap to set.": "Prøv {w} {u} — alle sæt nåede {reps} reps sidst. Tryk for at sætte.",
 "Try “squat 100 kilos for 5, 5 and 5”.": "Prøv “squat 100 kilo for 5, 5 og 5”.",
 "Type instead": "Skriv i stedet",
 "Type the number below instead.": "Skriv nummeret herunder i stedet.",
 "Type the number under the barcode instead.": "Skriv nummeret under stregkoden i stedet.",
 "Type what you ate or did": "Skriv, hvad du spiste eller lavede",
 "Typical size, not verified": "Typisk størrelse, ikke verificeret",
 "Understanding…": "Forstår…",
 "Undo": "Fortryd",
 "Unit not available": "Enhed ikke tilgængelig",
 "Units & language": "Enheder og sprog",
 "Units & locale": "Enheder og region",
 "Unknown exercise": "Ukendt øvelse",
 "Unlink superset": "Fjern superset",
 "Update": "Opdatér",
 "Updated {day}": "Opdaterede {day}",
 "Use previous": "Brug forrige",
 "Used for progression suggestions.": "Bruges til progressionsforslag.",
 "Verified serving size": "Verificeret portionsstørrelse",
 "View": "Se",
 "Volume": "Volumen",
 "Volume = weight × reps of completed working sets. Bodyweight and timed exercises count as zero here.": "Volumen = vægt × reps for afsluttede arbejdssæt. Kropsvægts- og tidsøvelser tæller som nul her.",
 "Volume = weight × reps of completed working sets. Warm-ups and unchecked sets are not counted.": "Volumen = vægt × reps for afsluttede arbejdssæt. Opvarmning og ikke-afkrydsede sæt tæller ikke med.",
 "Volume and progression": "Volumen og progression",
 "Waist": "Talje",
 "Warm-up sets": "Opvarmningssæt",
 "Water": "Vand",
 "Water quick amounts (ml)": "Hurtige vandmængder (ml)",
 "Week of": "Uge fra",
 "Week starts on": "Ugen starter på",
 "Weekly volume": "Ugentlig volumen",
 "Weigh at a consistent time — single readings are noisy; Aven charts a smoothed trend.": "Vej dig på samme tidspunkt — enkeltmålinger svinger; Aven viser en udjævnet tendens.",
 "Weigh the finished dish for accurate servings. Without it, the ingredient weights are added up.": "Vej den færdige ret for præcise portioner. Uden den lægges ingrediensernes vægt sammen.",
 "Weigh-ins": "Vejninger",
 "Weight": "Vægt",
 "Weight logged": "Vægt logget",
 "Weight × reps in one working set": "Vægt × reps i ét arbejdssæt",
 "What can you train with?": "Hvad kan du træne med?",
 "What should I call you?": "Hvad skal jeg kalde dig?",
 "What’s simulated or not built": "Hvad der er simuleret eller ikke bygget",
 "What’s your main goal?": "Hvad er dit hovedmål?",
 "Which days can you train?": "Hvilke dage kan du træne?",
 "Which exercise?": "Hvilken øvelse?",
 "Which “{q}”?": "Hvilken “{q}”?",
 "Whole recipe": "Hele opskriften",
 "Working sets": "Arbejdssæt",
 "Working…": "Arbejder…",
 "Workout": "Træning",
 "Workout deleted": "Træning slettet",
 "Workout discarded": "Træning kasseret",
 "Workout name": "Træningsnavn",
 "Workout summary": "Træningsoversigt",
 "Yes, delete everything": "Ja, slet alt",
 "Your copy of this food": "Din kopi af denne fødevare",
 "Your experience": "Din erfaring",
 "Your food": "Din fødevare",
 "Your macros add up to about {n} kcal, which differs from your calorie target.": "Dine makroer giver cirka {n} kcal, hvilket afviger fra dit kalorimål.",
 "Your name": "Dit navn",
 "Your plan": "Din plan",
 "Your recipe": "Din opskrift",
 "Your records": "Dine rekorder",
 "Your workout history is never changed by moving or skipping.": "Din træningshistorik ændres aldrig, når du flytter eller springer over.",
 "You’re offline": "Du er offline",
 "You’re offline — barcode lookup needs a connection. You can still add it yourself.": "Du er offline — opslag på stregkode kræver forbindelse. Du kan stadig tilføje det selv.",
 "avg": "gns.",
 "avg per logged day": "gns. pr. logget dag",
 "calculated": "beregnet",
 "change day": "skift dag",
 "copy": "kopi",
 "days a week": "dage om ugen",
 "days ago": "dage siden",
 "days logged": "dage logget",
 "done": "færdig",
 "e.g. 1 slice": "fx 1 skive",
 "e.g. Overnight oats": "fx Overnight oats",
 "e.g. Push day": "fx Skubbedag",
 "e.g. Restaurant pasta": "fx Restaurantpasta",
 "editable": "kan redigeres",
 "entries": "poster",
 "est. 1RM": "est. 1RM",
 "estimate": "estimat",
 "estimated portion": "estimeret portion",
 "exercises": "øvelser",
 "food entries": "madposter",
 "last": "sidst",
 "made up to show the app": "opdigtet for at vise appen",
 "measured": "målt",
 "more": "mere",
 "my equipment": "mit udstyr",
 "needs a prepared weight": "kræver en færdig vægt",
 "next": "næste",
 "no RPE/RIR": "ingen RPE/RIR",
 "no calorie data": "ingen kaloriedata",
 "no data": "ingen data",
 "nothing logged": "intet logget",
 "of": "af",
 "of target": "af mål",
 "optional": "valgfrit",
 "per": "pr.",
 "per serving": "pr. portion",
 "portion": "portion",
 "protein": "protein",
 "records": "rekorder",
 "record": "rekord",
 "reps": "reps",
 "reps best": "reps bedst",
 "required": "påkrævet",
 "rest": "hvil",
 "rotation": "rotation",
 "routines": "programmer",
 "saved only on this device, stripped of location data, and not included in exports unless you choose.": "gemmes kun på denne enhed, uden placeringsdata, og medtages ikke i eksport, medmindre du vælger det.",
 "serving": "portion",
 "servings": "portioner",
 "sessions": "træninger",
 "set": "sæt",
 "sets": "sæt",
 "short": "mangler",
 "some items lack data": "nogle poster mangler data",
 "speech-to-text is performed by your browser (on Chrome this is a Google cloud service). Aven itself never records or stores audio; it only reads the microphone level to animate the sphere while you speak.": "tale-til-tekst udføres af din browser (i Chrome er det en Google-skytjeneste). Aven optager eller gemmer aldrig selv lyd; den læser kun mikrofonniveauet for at animere kuglen, mens du taler.",
 "suggested": "foreslået",
 "summed": "lagt sammen",
 "superset": "superset",
 "target": "mål",
 "this week": "denne uge",
 "today": "i dag",
 "total": "i alt",
 "volume": "volumen",
 "was": "var",
 "weekly split": "ugentlig split",
 "weigh-ins": "vejninger",
 "when on, the text you search is sent to Aven’s lookup server, which forwards it to Open Food Facts and USDA FoodData Central. Nothing else is sent. Turn it off in Food & water.": "når det er slået til, sendes din søgetekst til Avens opslagsserver, som videresender den til Open Food Facts og USDA FoodData Central. Intet andet sendes. Slå det fra under Mad og vand.",
 "wk": "uge",
 "workouts": "træninger",
 "{name} removed": "{name} fjernet",
 "{n} added — tap + to add more": "{n} tilføjet — tryk + for at tilføje flere",
 "{n} entries cleared": "{n} poster ryddet",
 "{n} sets aren’t checked off. They will not be saved.": "{n} sæt er ikke afkrydset. De gemmes ikke.",
 "{n} to resolve": "{n} at afklare",
 "{n}-week streak of hitting your target": "{n} uger i træk med målet nået",
 "“200 grams of skyr and a banana” — review, then confirm.": "“200 gram skyr og en banan” — gennemse, og bekræft så.",
 "“200 grams of skyr, one banana and 60 grams of oats”": "“200 gram skyr, en banan og 60 gram havregryn”",
 "“Bench press 80 kilos for 8, 8 and 6”": "“Bænkpres 80 kilo for 8, 8 og 6”",
 "“{u}” can’t be converted for this food (no known density or portion). Enter grams:": "“{u}” kan ikke omregnes for denne fødevare (ingen kendt densitet eller portion). Skriv gram:",
 "Core": "Mave",
 "Cardio": "Cardio",
 "Bench": "Bænk",
 "Machine": "Maskine",
 "Smith machine": "Smithmaskine",
 "Cable": "Kabel",
 "Band": "Elastik",
 "Other": "Andet",
 "Push": "Skub",
 "Hinge": "Hofteløft",
 "Lunge": "Udfald",
 "Carry": "Bær",
 "Isolation": "Isolation",
 "Run": "Løb",
 "Walk": "Gåtur",
 "Cycle": "Cykling",
 "Swim": "Svømning",
 "Hike": "Vandretur",
 "Mobility": "Mobilitet",
 "Warm-up": "Opvarmning",
 "Recovery": "Restitution",
 "Activity": "Aktivitet",
 "Motion: system": "Bevægelse: system",
 "Reduced motion": "Reduceret bevægelse",
 "Full motion": "Fuld bevægelse",
 "Fixed": "Fast",
 "Tuesday": "Tirsdag",
 "Full gym": "Fuldt fitnesscenter",
 "Barbells, machines, cables": "Stænger, maskiner, kabler",
 "Home with barbell": "Hjemme med stang",
 "Barbell, dumbbells, bench": "Stang, håndvægte, bænk",
 "Home with dumbbells": "Hjemme med håndvægte",
 "Dumbbells, kettlebell, bands": "Håndvægte, kettlebell, elastikker",
 "Bodyweight only": "Kun kropsvægt",
 "No equipment": "Intet udstyr",
 "Main": "Hoved",
 "Legs": "Ben",
 "Upper A": "Overkrop A",
 "Upper B": "Overkrop B",
 "Lower A": "Underkrop A",
 "Lower B": "Underkrop B",
 "Full body A": "Hele kroppen A",
 "Full body B": "Hele kroppen B",
 "Full body C": "Hele kroppen C",
 "AI estimate": "AI-estimat",
 "Accurate": "Præcis",
 "Accurate = Whisper large-v3. Fast = large-v3-turbo (quicker, slightly less careful).": "Præcis = Whisper large-v3. Hurtig = large-v3-turbo (hurtigere, lidt mindre omhyggelig).",
 "Add a Gemini key in Settings → Voice & AI.": "Tilføj en Gemini-nøgle i Indstillinger → Stemme & AI.",
 "Add a free Gemini key and the Coach can answer from your own training, food and weight records. Everything else in Aven works without it.": "Tilføj en gratis Gemini-nøgle, så kan Coachen svare ud fra dine egne data om træning, mad og vægt. Alt andet i Aven virker uden.",
 "Add a key": "Tilføj en nøgle",
 "Add your Groq key in Settings → Voice & AI.": "Tilføj din Groq-nøgle i Indstillinger → Stemme & AI.",
 "Am I eating enough protein?": "Spiser jeg nok protein?",
 "Ask the Coach": "Spørg Coachen",
 "Ask anything about your training, food or weight. I only see a short summary computed on your device — I can advise, but I never change your data.": "Spørg om din træning, mad eller vægt. Jeg ser kun et kort resumé, der er regnet ud på din enhed — jeg kan rådgive, men jeg ændrer aldrig dine data.",
 "Auto": "Auto",
 "Auto works for mixed Danish/English, but fixing the language is more reliable.": "Auto virker til blandet dansk/engelsk, men et fast sprog er mere pålideligt.",
 "Build": "Byg",
 "Built by the Coach — check it before you rely on it.": "Bygget af Coachen — tjek den, før du stoler på den.",
 "Coach": "Coach",
 "Couldn’t reach Gemini. Check your connection — the key was saved anyway.": "Kunne ikke nå Gemini. Tjek din forbindelse — nøglen blev gemt alligevel.",
 "Couldn’t reach Gemini. Check your connection.": "Kunne ikke nå Gemini. Tjek din forbindelse.",
 "Couldn’t reach Groq. Check your connection — the key was saved anyway.": "Kunne ikke nå Groq. Tjek din forbindelse — nøglen blev gemt alligevel.",
 "Couldn’t reach Groq. Your recording is still here — retry, or type it.": "Kunne ikke nå Groq. Din optagelse er der stadig — prøv igen, eller skriv det.",
 "Couldn’t speak that.": "Kunne ikke sige det højt.",
 "Couldn’t transcribe that. Try again, or type it.": "Kunne ikke skrive det ud. Prøv igen, eller skriv det.",
 "Create routine": "Opret rutine",
 "Created": "Oprettet",
 "Describe the routine you want": "Beskriv den rutine, du vil have",
 "Didn’t catch anything. Try again.": "Fangede ikke noget. Prøv igen.",
 "Discard": "Kassér",
 "Estimate with Gemini": "Estimér med Gemini",
 "Estimated by Gemini for the portion you described": "Estimeret af Gemini for den portion, du beskrev",
 "Estimating…": "Estimerer…",
 "Fast": "Hurtig",
 "Free at aistudio.google.com. Used to read your sentences, estimate foods, build routines and talk in the Coach.": "Gratis på aistudio.google.com. Bruges til at forstå dine sætninger, estimere mad, bygge rutiner og tale i Coachen.",
 "Free at console.groq.com. Used only to turn your recording into text.": "Gratis på console.groq.com. Bruges kun til at lave din optagelse om til tekst.",
 "Gemini couldn’t be checked right now ({c}).": "Gemini kunne ikke tjekkes lige nu ({c}).",
 "Gemini couldn’t handle that request.": "Gemini kunne ikke håndtere den forespørgsel.",
 "Gemini failed. Try again.": "Gemini fejlede. Prøv igen.",
 "Gemini is busy right now. Try again in a moment.": "Gemini har travlt lige nu. Prøv igen om lidt.",
 "Gemini key works. Using {a} for dictation and {b} for the Coach.": "Gemini-nøglen virker. Bruger {a} til diktat og {b} til Coachen.",
 "Gemini key — understands you": "Gemini-nøgle — forstår dig",
 "Gemini rejected the key. Check it in Settings → Voice & AI.": "Gemini afviste nøglen. Tjek den i Indstillinger → Stemme & AI.",
 "Gemini rejected this key.": "Gemini afviste denne nøgle.",
 "Gemini sent an empty answer. Try again.": "Gemini sendte et tomt svar. Prøv igen.",
 "Gemini took too long. Try again.": "Gemini var for længe om det. Prøv igen.",
 "Gemini’s answer didn’t make sense, so it was ignored.": "Geminis svar gav ikke mening, så det blev ignoreret.",
 "Groq answered with an unexpected error ({c}).": "Groq svarede med en uventet fejl ({c}).",
 "Groq couldn’t transcribe that. Retry, or type it.": "Groq kunne ikke skrive det ud. Prøv igen, eller skriv det.",
 "Groq is rate-limiting right now. Wait a moment, then retry.": "Groq begrænser forespørgsler lige nu. Vent et øjeblik og prøv igen.",
 "Groq key works.": "Groq-nøglen virker.",
 "Groq key — hears you (Whisper)": "Groq-nøgle — hører dig (Whisper)",
 "Groq rejected the key. Check it in Settings → Voice & AI.": "Groq afviste nøglen. Tjek den i Indstillinger → Stemme & AI.",
 "Groq rejected this key.": "Groq afviste denne nøgle.",
 "Groq took too long. Your recording is still here — retry, or type it.": "Groq var for længe om det. Din optagelse er der stadig — prøv igen, eller skriv det.",
 "Heard by Groq": "Hørt af Groq",
 "Heard by your browser": "Hørt af din browser",
 "Hide key": "Skjul nøgle",
 "How is my week going?": "Hvordan går min uge?",
 "If off, or if Gemini fails, the built-in parser is used.": "Hvis slået fra, eller hvis Gemini fejler, bruges den indbyggede tolker.",
 "Is my weight moving the right way?": "Bevæger min vægt sig i den rigtige retning?",
 "Language you speak": "Sprog du taler",
 "Left out (not in your exercise library): {list}": "Udeladt (findes ikke i dit øvelsesbibliotek): {list}",
 "Let Gemini understand dictation": "Lad Gemini forstå diktat",
 "Listening… tap the mic to send": "Lytter… tryk på mikrofonen for at sende",
 "Message the Coach": "Skriv til Coachen",
 "Microphone permission was denied. You can allow it in your browser settings, or type instead.": "Mikrofontilladelsen blev afvist. Du kan give den i browserens indstillinger, eller skrive i stedet.",
 "No microphone was found.": "Der blev ikke fundet nogen mikrofon.",
 "Not exact. Logged as a quick entry labelled “AI estimate”.": "Ikke præcist. Logges som en hurtig indtastning mærket “AI-estimat”.",
 "Open and edit": "Åbn og rediger",
 "Optional: Groq hears, Gemini understands": "Valgfrit: Groq hører, Gemini forstår",
 "Or add a Groq key in Settings → Voice & AI.": "Eller tilføj en Groq-nøgle i Indstillinger → Stemme & AI.",
 "Paste a new key to replace it": "Indsæt en ny nøgle for at erstatte den",
 "Paste your key": "Indsæt din nøgle",
 "Proposed routine — not saved yet": "Foreslået rutine — ikke gemt endnu",
 "Recording": "Optager",
 "Remove key": "Fjern nøgle",
 "Retry transcription": "Prøv transskription igen",
 "Routine created": "Rutine oprettet",
 "Save and test": "Gem og test",
 "Send": "Send",
 "Show key": "Vis nøgle",
 "Speak": "Tal",
 "Speak Coach answers": "Læs Coachens svar højt",
 "Speak naturally. Your words appear after you tap “Done speaking”.": "Tal helt naturligt. Dine ord vises, når du trykker “Færdig med at tale”.",
 "Stop": "Stop",
 "Stop and send": "Stop og send",
 "Stop speaking": "Stop oplæsning",
 "Stopped.": "Stoppet.",
 "Test again": "Test igen",
 "Testing…": "Tester…",
 "That Gemini model isn’t available for your key.": "Den Gemini-model er ikke tilgængelig for din nøgle.",
 "That didn’t produce a usable routine from the exercises you have. Try describing it differently.": "Det gav ikke en brugbar rutine ud fra de øvelser, du har. Prøv at beskrive det anderledes.",
 "The Coach is an AI and can be wrong. It isn’t medical advice. Your messages and a summary of your records are sent to Google Gemini.": "Coachen er en AI og kan tage fejl. Det er ikke lægelig rådgivning. Dine beskeder og et resumé af dine data sendes til Google Gemini.",
 "The Coach needs a Gemini key": "Coachen skal bruge en Gemini-nøgle",
 "The microphone couldn’t start.": "Mikrofonen kunne ikke starte.",
 "The microphone is in use by something else.": "Mikrofonen bruges af noget andet.",
 "The microphone isn’t available. Check the permission, or type.": "Mikrofonen er ikke tilgængelig. Tjek tilladelsen, eller skriv.",
 "Thinking…": "Tænker…",
 "This browser can’t record audio.": "Denne browser kan ikke optage lyd.",
 "This browser can’t record audio. Type instead.": "Denne browser kan ikke optage lyd. Skriv i stedet.",
 "Today’s free Gemini quota is used up. It resets at midnight Pacific time.": "Dagens gratis Gemini-kvote er brugt. Den nulstilles ved midnat i Stillehavstid.",
 "Transcribing…": "Skriver ud…",
 "Transcription": "Transskription",
 "Used the built-in parser instead.": "Brugte den indbyggede tolker i stedet.",
 "Uses Gemini’s voice. Off by default; text always shows.": "Bruger Geminis stemme. Slået fra som standard; teksten vises altid.",
 "Voice": "Stemme",
 "Voice & AI": "Stemme & AI",
 "What leaves your phone": "Hvad forlader din telefon",
 "What should I train next?": "Hvad skal jeg træne næste gang?",
 "Your recording is sent to Groq to be transcribed, and the text to Google Gemini to be understood. Aven doesn’t store the audio. Keys stay on this device.": "Din optagelse sendes til Groq for at blive skrevet ud, og teksten til Google Gemini for at blive forstået. Aven gemmer ikke lyden. Nøgler bliver på denne enhed.",
 "Your recording is sent to Groq to be transcribed. Aven doesn’t store the audio. Keys stay on this device.": "Din optagelse sendes til Groq for at blive skrevet ud. Aven gemmer ikke lyden. Nøgler bliver på denne enhed.",
 "You’re offline, so nothing was sent. Your recording is still here — retry when you’re back online, or type it.": "Du er offline, så intet blev sendt. Din optagelse er der stadig — prøv igen, når du er online, eller skriv det.",
 "You’re offline.": "Du er offline.",
 "check before logging": "tjek før du logger",
 "only if you add keys. Text you dictate or ask the Coach (plus a short summary of your targets and training for the Coach) goes to Google Gemini. API keys are stored only in this browser and are never part of exports or backups.": "kun hvis du tilføjer nøgler. Tekst, du dikterer eller spørger Coachen om (plus et kort resumé af dine mål og din træning til Coachen), går til Google Gemini. API-nøgler gemmes kun i denne browser og er aldrig en del af eksport eller backup.",
 "understood by Gemini": "forstået af Gemini",
 "understood on this device": "forstået på denne enhed",
 "without a Groq key, speech-to-text is performed by your browser (on Chrome this is a Google cloud service). With a Groq key, your recording is sent to Groq instead. Either way Aven never stores audio; it only reads the microphone level to animate the sphere while you speak.": "uden Groq-nøgle klarer din browser talegenkendelsen (i Chrome er det en Google-skytjeneste). Med en Groq-nøgle sendes din optagelse til Groq i stedet. Uanset hvad gemmer Aven aldrig lyd; den læser kun mikrofonniveauet for at animere kuglen, mens du taler.",
 "your recording goes to Groq; the text of what you said (and, in the Coach, a short summary of your targets and recent training) goes to Google Gemini. Free-tier terms apply to both — free Gemini traffic may be used by Google to improve its products, so don’t put anything in there you wouldn’t want that. Aven stores no audio. The keys live only in this browser on this device: they are not in backups or exports, and “Delete everything” removes them.": "din optagelse går til Groq; teksten af det, du sagde (og i Coachen et kort resumé af dine mål og seneste træning), går til Google Gemini. Vilkårene for gratis brug gælder for begge — gratis Gemini-trafik kan bruges af Google til at forbedre deres produkter, så skriv ikke noget dér, du ikke vil have brugt sådan. Aven gemmer ingen lyd. Nøglerne findes kun i denne browser på denne enhed: de er ikke med i backup eller eksport, og “Slet alt” fjerner dem.",
 "Optional, and free. Aven works without them; with them it hears you better (Danish too) and the Coach can talk and act.": "Valgfrit og gratis. Aven virker uden; med dem hører den dig bedre (også dansk), og Coachen kan tale og handle.",
 "First session": "Første pas",
 "Log weight": "Log vægt",
 "Over": "Over",
 "kcal": "kcal",
 "kcal left": "kcal tilbage",
 "Audio goes to Groq, text to Gemini. Aven stores nothing.": "Lyd går til Groq, tekst til Gemini. Aven gemmer intet.",
 "Audio goes to Groq. Aven stores nothing.": "Lyd går til Groq. Aven gemmer intet.",
 "Your browser transcribes this. Aven stores nothing.": "Din browser skriver det ud. Aven gemmer intet.",
 "Continue workout": "Fortsæt træning",
 "& recovery": "& restitution",
 "Analyse again": "Analysér igen",
 "Camera": "Kamera",
 "Couldn’t read that image.": "Kunne ikke læse billedet.",
 "Estimated by Gemini from the photo — not exact. Logged as “AI estimate”.": "Estimeret af Gemini ud fra billedet — ikke præcist. Logges som “AI-estimat”.",
 "From gallery": "Fra galleri",
 "Hint": "Hint",
 "Intensity": "Intensitet",
 "Log a session": "Log en træning",
 "Log wrestling": "Log brydning",
 "Mat time": "Tid på måtten",
 "Mat time per week": "Tid på måtten pr. uge",
 "Needs a Gemini key": "Kræver en Gemini-nøgle",
 "New personal record": "Ny personlig rekord",
 "New personal records": "Nye personlige rekorder",
 "Optional hint, e.g. “with rice, no sauce”": "Valgfrit hint, fx “med ris, uden sovs”",
 "Retake": "Tag igen",
 "Rounds": "Runder",
 "Save session": "Gem træning",
 "Snap your plate": "Fotografér din tallerken",
 "Take a photo": "Tag et billede",
 "That doesn’t look like food. Try another photo.": "Det ligner ikke mad. Prøv et andet billede.",
 "What you drilled, who you rolled with…": "Hvad I trænede, hvem du brød med…",
 "Wrestling": "Brydning",
 "Wrestling logged": "Brydning logget",
 "rounds": "runder",
 "{n} new records": "{n} nye rekorder",
 "Easy": "Let",
 "Hard": "Hård",
 "Max": "Max",
 "rep": "gentagelse",
 "A workout is already running": "Et træningspas kører allerede",
 "Bench press 80 kg for 8, 8, 6": "Bænkpres 80 kg i 8, 8, 6",
 "Calorie target": "Kalorie-mål",
 "Carb target": "Kulhydrat-mål",
 "Couldn’t change that setting": "Kunne ikke ændre den indstilling",
 "Activity removed": "Aktivitet fjernet",
 "Add face pulls to my workout": "Tilføj face pulls til min træning",
 "Added to favourites": "Tilføjet til favoritter",
 "Build me a push, pull, legs routine": "Lav mig en push-, pull- og benprogram",
 "Copied to {where}": "Kopieret til {where}",
 "Couldn’t add that": "Kunne ikke tilføje det",
 "Couldn’t build that routine": "Kunne ikke lave det program",
 "Couldn’t change that routine": "Kunne ikke ændre det program",
 "Couldn’t find that activity": "Kunne ikke finde den aktivitet",
 "Couldn’t find that exercise": "Kunne ikke finde den øvelse",
 "Couldn’t find that exercise in the routine": "Kunne ikke finde den øvelse i programmet",
 "Couldn’t find that exercise in the workout": "Kunne ikke finde den øvelse i træningen",
 "Couldn’t find that routine": "Kunne ikke finde det program",
 "Couldn’t find that weigh-in": "Kunne ikke finde den vejning",
 "Couldn’t find that workout": "Kunne ikke finde den træning",
 "Couldn’t replace that": "Kunne ikke erstatte det",
 "Discard this workout?": "Kassér denne træning?",
 "Exercise swapped": "Øvelse byttet",
 "Food saved": "Mad gemt",
 "Make my last set 2.5 kg heavier": "Gør mit sidste sæt 2,5 kg tungere",
 "Meal saved": "Måltid gemt",
 "Move {food} to {meal}": "Flyt {food} til {meal}",
 "Moved to {where}": "Flyttet til {where}",
 "No workout to change": "Ingen træning at ændre",
 "Note added": "Note tilføjet",
 "Nothing to move": "Intet at flytte",
 "Nothing to remove": "Intet at fjerne",
 "Plan updated": "Plan opdateret",
 "Put {routine} on Friday": "Sæt {routine} på fredag",
 "Remove {food}": "Fjern {food}",
 "Removed from favourites": "Fjernet fra favoritter",
 "Removed from workout": "Fjernet fra træningen",
 "Replace {food} with a banana": "Erstat {food} med en banan",
 "Replaced": "Erstattet",
 "Routine updated": "Program opdateret",
 "Save today’s lunch as a meal": "Gem dagens frokost som et måltid",
 "Saved and logged": "Gemt og logget",
 "Say which routine to change, or start a workout first.": "Sig hvilket program der skal ændres, eller start en træning først.",
 "Set corrected": "Sæt rettet",
 "That set doesn’t exist": "Det sæt findes ikke",
 "Weigh-in removed": "Vejning fjernet",
 "What should I change in {routine}?": "Hvad skal jeg ændre i {routine}?",
 "added": "tilføjet",
 "items": "ting",
 "not in this routine": "ikke i dette program",
 "removed": "fjernet",
 "sets done": "sæt færdige",
 "Already there": "Allerede der",
 "Log, change or ask anything.": "Log, ret eller spørg om hvad som helst.",
 "Add a Gemini key to chat.": "Tilføj en Gemini-nøgle for at chatte.",
 "Shows your real refresh rate, top-left.": "Viser din rigtige opdateringsfrekvens øverst til venstre.",
 "Draws motion at your screen’s full rate (up to 120 Hz).": "Tegner bevægelse med skærmens fulde hastighed (op til 120 Hz).",
 "Couldn’t do that": "Kunne ikke gøre det",
 "Couldn’t find that in the log": "Kunne ikke finde det i loggen",
 "Couldn’t change that": "Kunne ikke ændre det",
 "Corrected": "Rettet",
 "values": "værdier",
 "totals": "totaler",
 "Couldn’t log that": "Kunne ikke logge det",
 "Couldn’t reach Groq. Try again, or type it.": "Kunne ikke nå Groq. Prøv igen, eller skriv det.",
 "Couldn’t start that": "Kunne ikke starte det",
 "Default rest": "Standardhvile",
 "Distance unit": "Afstandsenhed",
 "Effort scale": "Anstrengelsesskala",
 "Empty workout": "Tomt pas",
 "Fat target": "Fedt-mål",
 "Finish and save": "Afslut og gem",
 "Finish this workout?": "Afslut dette pas?",
 "Gemini wasn’t available, so I used the built-in reader.": "Gemini var ikke tilgængelig, så jeg brugte den indbyggede læser.",
 "Groq couldn’t transcribe that. Try again, or type it.": "Groq kunne ikke transskribere det. Prøv igen, eller skriv det.",
 "Groq is rate-limiting right now. Wait a moment, then try again.": "Groq begrænser forbruget lige nu. Vent lidt og prøv igen.",
 "Groq took too long. Try again, or type it.": "Groq var for længe om det. Prøv igen, eller skriv det.",
 "Haptics": "Haptik",
 "How do I change the theme?": "Hvordan skifter jeg tema?",
 "Log a banana": "Log en banan",
 "Logged to {meal}": "Logget til {meal}",
 "No routine with that name": "Ingen rutine med det navn",
 "No workout is running": "Intet pas kører",
 "Not found — add it from the Food tab": "Ikke fundet — tilføj det fra Mad-fanen",
 "Not in your exercise library": "Ikke i dit øvelsesbibliotek",
 "Open workout": "Åbn pas",
 "Opening {screen}": "Åbner {screen}",
 "Protein target": "Protein-mål",
 "Setting changed": "Indstilling ændret",
 "Sound": "Lyd",
 "Tell me what you ate or lifted, ask about your training or the app, or ask me to do something. I log it for you — and every change has an Undo.": "Fortæl mig, hvad du har spist eller løftet, spørg om din træning eller appen, eller bed mig gøre noget. Jeg logger det for dig — og alt kan fortrydes.",
 "To chat or ask about the app I need a Gemini key (Settings → Voice & AI). I can still log what you tell me, like “200 g skyr” or “bench 80 for 8”.": "For at chatte eller spørge om appen skal jeg bruge en Gemini-nøgle (Indstillinger → Stemme & AI). Jeg kan stadig logge det, du fortæller mig, f.eks. “200 g skyr” eller “bænk 80 i 8”.",
 "Total": "I alt",
 "Undone": "Fortrudt",
 "Undone.": "Fortrudt.",
 "Water logged": "Vand logget",
 "Water target": "Vand-mål",
 "Weight unit": "Vægtenhed",
 "Which one?": "Hvilken?",
 "Without a Gemini key I can still log simple things, but not chat. Add one in Settings → Voice & AI.": "Uden en Gemini-nøgle kan jeg stadig logge simple ting, men ikke chatte. Tilføj en i Indstillinger → Stemme & AI.",
 "Workout started": "Pas startet",
 "Yesterday": "I går",
 "You’re offline, so nothing was sent. Type it instead.": "Du er offline, så intet blev sendt. Skriv det i stedet.",
 "best match for": "bedste match for",
 "typical portion": "typisk portion",
 "Say more": "Sig mere",
 "Speak naturally. I stop listening when you pause.": "Tal helt naturligt. Jeg stopper med at lytte, når du holder pause.",
 "Tap the sphere to say more": "Tryk på kuglen for at sige mere",
 "“Log a banana” · “Bench 100 kg for 8, 8 and 6” · “How do I change the theme?”": "“Log en banan” · “Bænkpres 100 kg 8, 8 og 6” · “Hvordan skifter jeg tema?”",
 "Frame rate readout": "Billedhastighed",
 "Shows the refresh rate your phone and browser really give the app, in the top-left corner. 120 Hz with 0 late is the best case; a steady 60 Hz means the browser or phone caps it.": "Viser den opdateringshastighed, din telefon og browser faktisk giver appen, i øverste venstre hjørne. 120 Hz med 0 forsinkede er bedst; et stabilt 60 Hz betyder, at browseren eller telefonen begrænser den.",
 "{n} sets done": "{n} sæt udført",
 "High refresh rate": "Høj opdateringshastighed",
 "Popups, the live workout and the page behind them are drawn by the browser itself, at your screen’s full rate (up to 120 Hz), instead of by the app at up to 60. Turn off if anything looks wrong.": "Pop-ups, den aktive træning og siden bag dem tegnes af browseren selv i skærmens fulde hastighed (op til 120 Hz) i stedet for af appen med op til 60. Slå fra, hvis noget ser forkert ud.",
 "AI can be wrong, and isn’t medical advice. Messages go to Google Gemini.": "AI kan tage fejl og er ikke lægelig rådgivning. Beskeder sendes til Google Gemini.",
 "Continue in Coach": "Fortsæt i Coach",
 "Couldn’t read that aloud.": "Kunne ikke læse det højt.",
 "Read aloud": "Læs højt",
 "Voice for read-aloud": "Stemme til oplæsning",
 "Answers are only read aloud when you tap ▶ next to them.": "Svar læses kun højt, når du trykker på ▶ ved siden af dem.",
 "Stop reading": "Stop oplæsning",
 "Suggest macros": "Foreslå makroer",
 "Save as new": "Gem som ny",
 "Update {routine}": "Opdatér {routine}",
 "{n} % volume vs last time": "{n} % volumen ift. sidst",
 "Each routine on the same weekdays every week.": "Hvert program på de samme ugedage hver uge.",
 "Routines in order: the next one is whatever follows your last workout, on any day.": "Programmerne i rækkefølge: det næste er det, der følger efter din sidste træning, uanset dag.",
 "Alert when rest is over": "Besked når hvilen er slut",
 "All sets done": "Alle sæt er klaret",
 "Allow": "Tillad",
 "Even with the phone in your pocket.": "Også med telefonen i lommen.",
 "Get an alert when rest is over, even with the phone in your pocket?": "Vil du have besked, når hvilen er slut – også med telefonen i lommen?",
 "Next": "Næste",
 "Notifications are blocked for Aven in your browser settings.": "Notifikationer er blokeret for Aven i browserens indstillinger.",
 "Min reps": "Min. gentagelser",
 "Max reps": "Maks. gentagelser",
 "at least": "mindst",
 "Some foods have no value for this, so the real total is a little higher.": "Nogle fødevarer mangler en værdi her, så det reelle tal er lidt højere.",
 "Microphone": "Mikrofon",
 "Phone": "Telefon",
 "Earbuds": "Høretelefoner",
 "With earbuds in, the phone’s own mic hears you better and keeps your music playing.": "Med høretelefoner i hører telefonens egen mikrofon dig bedre, og musikken spiller videre.",
 "Record stutters": "Optag hak",
 "Recording — use the app as normal. {m} left, {n} caught.": "Optager – brug appen som normalt. {m} tilbage, {n} fanget.",
 "Notes every frame your phone had to wait for, for five minutes, so the next fix is aimed at what you felt. Only timings and screen names.": "Noterer hvert billede, telefonen måtte vente på, i fem minutter, så næste rettelse rammer det, du mærkede. Kun tider og skærmnavne.",
 "Start recording": "Start optagelse",
 "Copy report": "Kopiér rapport",
 "Report copied": "Rapport kopieret",
 "Couldn’t copy": "Kunne ikke kopiere",
 "No sets yet": "Ingen sæt endnu",
 "Tell the orb what you did": "Fortæl kuglen, hvad du lavede",
 "{n} sets aren’t ticked. Only the ticked ones are saved.": "{n} sæt er ikke krydset af. Kun de afkrydsede gemmes.",
 "Finish and save 1 set": "Afslut og gem 1 sæt",
 "AI can be wrong, and isn’t medical advice. Messages go to OpenAI (GPT-6.1 Sol).": "AI kan tage fejl og er ikke lægelig rådgivning. Beskeder sendes til OpenAI (GPT-6.1 Sol).",
 "Add an AI key to chat.": "Tilføj en AI-nøgle for at chatte.",
 "Brain": "Hjerne",
 "Couldn’t reach OpenAI. Check your connection — the key was saved anyway.": "Kunne ikke nå OpenAI. Tjek din forbindelse — nøglen er gemt alligevel.",
 "Couldn’t reach OpenAI. Check your connection.": "Kunne ikke nå OpenAI. Tjek din forbindelse.",
 "Drag to reorder": "Træk for at flytte",
 "From platform.openai.com. Billed per use (about 0.20 kr per orb command on Medium, 0.40–0.50 kr on High). Set a monthly spend limit there. Gemini stays the free fallback and reads answers aloud.": "Fra platform.openai.com. Betales pr. brug (ca. 0,20 kr. pr. orb-kommando på Mellem, 0,40–0,50 kr. på Høj). Sæt en månedlig udgiftsgrænse dér. Gemini er stadig den gratis reserve og læser svar højt.",
 "GPT-6.1 Sol": "GPT-6.1 Sol",
 "GPT-6.1 Sol couldn’t handle that request.": "GPT-6.1 Sol kunne ikke håndtere den forespørgsel.",
 "GPT-6.1 Sol failed. Try again.": "GPT-6.1 Sol fejlede. Prøv igen.",
 "GPT-6.1 Sol isn’t enabled for this OpenAI key.": "GPT-6.1 Sol er ikke slået til for denne OpenAI-nøgle.",
 "GPT-6.1 Sol sent an empty answer. Try again.": "GPT-6.1 Sol sendte et tomt svar. Prøv igen.",
 "GPT-6.1 Sol took too long. Try again.": "GPT-6.1 Sol var for længe om det. Prøv igen.",
 "GPT-6.1 Sol wasn’t available, so Gemini answered.": "GPT-6.1 Sol var ikke tilgængelig, så Gemini svarede.",
 "GPT-6.1 Sol’s answer didn’t make sense, so it was ignored.": "GPT-6.1 Sols svar gav ikke mening, så det blev ignoreret.",
 "Gemini": "Gemini",
 "High": "Høj",
 "High thinks longer and costs about twice as much. Medium keeps the orb quick for logging.": "Høj tænker længere og koster cirka det dobbelte. Mellem holder orben hurtig til logning.",
 "Medium": "Mellem",
 "Needs an AI key": "Kræver en AI-nøgle",
 "OpenAI answered with an unexpected error ({c}).": "OpenAI svarede med en uventet fejl ({c}).",
 "OpenAI is busy right now. Try again in a moment.": "OpenAI har travlt lige nu. Prøv igen om lidt.",
 "OpenAI key works. GPT-6.1 Sol now answers the orb and the Coach.": "OpenAI-nøglen virker. GPT-6.1 Sol svarer nu i orben og Coach.",
 "OpenAI key — GPT-6.1 Sol (paid)": "OpenAI-nøgle — GPT-6.1 Sol (betalt)",
 "OpenAI rejected the key. Check it in Settings → Voice & AI.": "OpenAI afviste nøglen. Tjek den i Indstillinger → Stemme & AI.",
 "OpenAI rejected this key.": "OpenAI afviste denne nøgle.",
 "Optional. Aven works without them; with them it hears you better (Danish too) and the Coach can talk and act. Groq and Gemini are free; OpenAI is paid.": "Valgfrit. Aven virker uden dem; med dem hører den dig bedre (også på dansk), og Coach kan tale og handle. Groq og Gemini er gratis; OpenAI koster penge.",
 "The key works, but GPT-6.1 Sol isn’t enabled on this OpenAI account.": "Nøglen virker, men GPT-6.1 Sol er ikke slået til på denne OpenAI-konto.",
 "Thinking — Coach": "Tænkning — Coach",
 "Thinking — orb": "Tænkning — orb",
 "To chat or ask about the app I need an AI key (Settings → Voice & AI). I can still log what you tell me, like “200 g skyr” or “bench 80 for 8”.": "For at chatte eller spørge om appen skal jeg have en AI-nøgle (Indstillinger → Stemme & AI). Jeg kan stadig logge det, du fortæller mig, fx “200 g skyr” eller “bænk 80 til 8”.",
 "With GPT-6.1 Sol on, that text (and plate photos) goes to OpenAI instead, sent with “don’t store”; OpenAI doesn’t train on API data.": "Med GPT-6.1 Sol slået til går den tekst (og tallerkenfotos) til OpenAI i stedet, sendt med “gem ikke”; OpenAI træner ikke på API-data.",
 "Your OpenAI account is out of credit or over its limit.": "Din OpenAI-konto er løbet tør for kredit eller over sin grænse.",
 "Your OpenAI account is out of credit, so Gemini answered.": "Din OpenAI-konto er løbet tør for kredit, så Gemini svarede.",
 "The AI wasn’t available, so I used the built-in reader.": "AI'en var ikke tilgængelig, så jeg brugte den indbyggede læser.",
};
