import { launch, wait } from './lib.mjs';
const { b, ctx, p } = await launch({});
await p.addInitScript(() => { if (!localStorage.getItem('aven.v1')) localStorage.setItem('aven.v1', JSON.stringify({ v: 1, settings: { language: 'da', onboarded: true, name: 'Omar', goals: { kcal: 2600, protein: 170, waterMl: 3000 } } })); });
await p.goto('http://127.0.0.1:5173/'); await wait(p, 1200);
await p.screenshot({ path: 'shots/da-today.png' });
await p.locator('.tabbar').getByText('Mad', { exact: true }).click(); await wait(p, 800);
await p.screenshot({ path: 'shots/da-food.png' });
await p.locator('.tabbar').getByText('Træn', { exact: true }).click(); await wait(p, 800);
await p.screenshot({ path: 'shots/da-train.png' });
await b.close();
